/* cronotas.c generated by valac 0.40.8, the Vala compiler
 * generated from cronotas.vala, do not modify */

/*
Cronotas (c) Didapax Sistem Daniel Alfonsi 
2019
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <sqlite3.h>
#include <stdio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>


#define CRONO_TYPE_CRONOTAS (crono_cronotas_get_type ())
#define CRONO_CRONOTAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_CRONOTAS, cronocronotas))
#define CRONO_CRONOTAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_CRONOTAS, cronocronotasClass))
#define CRONO_IS_CRONOTAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_CRONOTAS))
#define CRONO_IS_CRONOTAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_CRONOTAS))
#define CRONO_CRONOTAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_CRONOTAS, cronocronotasClass))

typedef struct _cronocronotas cronocronotas;
typedef struct _cronocronotasClass cronocronotasClass;
typedef struct _cronocronotasPrivate cronocronotasPrivate;

#define CRONO_TYPE_TAB (crono_tab_get_type ())
#define CRONO_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_TAB, cronotab))
#define CRONO_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_TAB, cronotabClass))
#define CRONO_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_TAB))
#define CRONO_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_TAB))
#define CRONO_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_TAB, cronotabClass))

typedef struct _cronotab cronotab;
typedef struct _cronotabClass cronotabClass;

#define CRONO_TYPE_DIALOG_JORNADA (crono_dialog_jornada_get_type ())
#define CRONO_DIALOG_JORNADA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornada))
#define CRONO_DIALOG_JORNADA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornadaClass))
#define CRONO_IS_DIALOG_JORNADA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_DIALOG_JORNADA))
#define CRONO_IS_DIALOG_JORNADA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_DIALOG_JORNADA))
#define CRONO_DIALOG_JORNADA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornadaClass))

typedef struct _cronodialog_jornada cronodialog_jornada;
typedef struct _cronodialog_jornadaClass cronodialog_jornadaClass;

#define CRONO_TYPE_TEMPO (crono_tempo_get_type ())
#define CRONO_TEMPO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_TEMPO, cronotempo))
#define CRONO_TEMPO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_TEMPO, cronotempoClass))
#define CRONO_IS_TEMPO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_TEMPO))
#define CRONO_IS_TEMPO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_TEMPO))
#define CRONO_TEMPO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_TEMPO, cronotempoClass))

typedef struct _cronotempo cronotempo;
typedef struct _cronotempoClass cronotempoClass;

#define CRONO_TYPE_CONFIG (crono_config_get_type ())
#define CRONO_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_CONFIG, cronoconfig))
#define CRONO_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_CONFIG, cronoconfigClass))
#define CRONO_IS_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_CONFIG))
#define CRONO_IS_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_CONFIG))
#define CRONO_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_CONFIG, cronoconfigClass))

typedef struct _cronoconfig cronoconfig;
typedef struct _cronoconfigClass cronoconfigClass;
enum  {
	CRONO_CRONOTAS_0_PROPERTY,
	CRONO_CRONOTAS_NUM_PROPERTIES
};
static GParamSpec* crono_cronotas_properties[CRONO_CRONOTAS_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define CRONO_TYPE_F_CONFIG (crono_f_config_get_type ())
typedef struct _cronof_config cronof_config;
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _cronocronotas {
	GtkWindow parent_instance;
	cronocronotasPrivate * priv;
};

struct _cronocronotasClass {
	GtkWindowClass parent_class;
};

struct _cronocronotasPrivate {
	cronotab* separar;
	GtkMenu* menu_system;
	cronodialog_jornada* jornadas;
	cronotempo* temporizador;
	cronoconfig* dialog_config;
	GtkMenuItem* menu_trabajo;
	guint time_trabajo;
	gint min_trabajo;
	gint hour_trabajo;
	gint num_jornada;
	gint ht;
	gboolean tra;
	gboolean state_trabajo;
	gboolean play;
	gboolean stop;
	gboolean check_jornada;
};

struct _cronof_config {
	gchar* id;
	gchar* ruta;
	gchar* color;
};


extern GtkStatusIcon* crono_tray_icon;
GtkStatusIcon* crono_tray_icon = NULL;
extern gchar* crono_lcd;
gchar* crono_lcd = NULL;
static gpointer crono_cronotas_parent_class = NULL;
extern cronof_config crono_fconfig;
extern gint crono_max_nota;
extern sqlite3* crono_db;
extern gint crono_rc;

GType crono_cronotas_get_type (void) G_GNUC_CONST;
GType crono_tab_get_type (void) G_GNUC_CONST;
GType crono_dialog_jornada_get_type (void) G_GNUC_CONST;
GType crono_tempo_get_type (void) G_GNUC_CONST;
GType crono_config_get_type (void) G_GNUC_CONST;
#define CRONO_CRONOTAS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CRONO_TYPE_CRONOTAS, cronocronotasPrivate))
cronocronotas* crono_cronotas_new (void);
cronocronotas* crono_cronotas_construct (GType object_type);
void crono_init_datos (void);
void crono_cronotas_init (cronocronotas* self);
GType crono_f_config_get_type (void) G_GNUC_CONST;
cronof_config* crono_f_config_dup (const cronof_config* self);
void crono_f_config_free (cronof_config* self);
void crono_f_config_copy (const cronof_config* self,
                          cronof_config* dest);
void crono_f_config_destroy (cronof_config* self);
void crono_cronotas_create_menu_system (cronocronotas* self);
static void crono_cronotas_menu_system_popup (cronocronotas* self,
                                       guint button,
                                       guint time);
static void _crono_cronotas_menu_system_popup_gtk_status_icon_popup_menu (GtkStatusIcon* _sender,
                                                                   guint button,
                                                                   guint activate_time,
                                                                   gpointer self);
cronotab* crono_tab_new (gint num);
cronotab* crono_tab_construct (GType object_type,
                               gint num);
void crono_cronotas_actualiza_tray (cronocronotas* self);
void crono_cronotas_aplicar_color (cronocronotas* self,
                                   const gchar* color);
gboolean crono_cronotas_on_time_trabajo (cronocronotas* self);
gchar* crono_formatT (gint valor);
void crono_guarda_trabajo (gint hx,
                           gint mx,
                           const gchar* lcd);
void crono_cronotas_time_trabajo_play (cronocronotas* self);
static gboolean _crono_cronotas_on_time_trabajo_gsource_func (gpointer self);
void crono_cronotas_init_trabajo (cronocronotas* self);
gboolean crono_now_tareas (void);
gint crono_count_jornadas (void);
static void __lambda6_ (cronocronotas* self);
gint crono_crear_ficha (void);
static void ___lambda6__gtk_menu_item_activate (GtkMenuItem* _sender,
                                         gpointer self);
static void __lambda7_ (cronocronotas* self);
cronotempo* crono_tempo_new (void);
cronotempo* crono_tempo_construct (GType object_type);
static void ___lambda7__gtk_menu_item_activate (GtkMenuItem* _sender,
                                         gpointer self);
static void _crono_cronotas_time_trabajo_play_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                               gpointer self);
static void __lambda8_ (cronocronotas* self);
cronodialog_jornada* crono_dialog_jornada_new (void);
cronodialog_jornada* crono_dialog_jornada_construct (GType object_type);
static void ___lambda8__gtk_menu_item_activate (GtkMenuItem* _sender,
                                         gpointer self);
static void __lambda9_ (cronocronotas* self);
cronoconfig* crono_config_new (void);
cronoconfig* crono_config_construct (GType object_type);
static void ___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender,
                                         gpointer self);
static void crono_cronotas_about_clicked (cronocronotas* self);
static void _crono_cronotas_about_clicked_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                           gpointer self);
static void _gtk_main_quit_gtk_menu_item_activate (GtkMenuItem* _sender,
                                            gpointer self);
gint crono_cronotas_main (gchar** args,
                          int args_length1);
static void crono_cronotas_finalize (GObject * obj);


cronocronotas*
crono_cronotas_construct (GType object_type)
{
	cronocronotas * self = NULL;
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self = (cronocronotas*) g_object_new (object_type, NULL);
#line 32 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_init_datos ();
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_init (self);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return self;
#line 213 "cronotas.c"
}


cronocronotas*
crono_cronotas_new (void)
{
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return crono_cronotas_construct (CRONO_TYPE_CRONOTAS);
#line 222 "cronotas.c"
}


static void
_crono_cronotas_menu_system_popup_gtk_status_icon_popup_menu (GtkStatusIcon* _sender,
                                                              guint button,
                                                              guint activate_time,
                                                              gpointer self)
{
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_menu_system_popup ((cronocronotas*) self, button, activate_time);
#line 234 "cronotas.c"
}


void
crono_cronotas_init (cronocronotas* self)
{
	gchar* _tmp0_;
	cronof_config _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	GtkStatusIcon* _tmp5_;
	GtkStatusIcon* _tmp6_;
	GtkStatusIcon* _tmp7_;
	cronof_config _tmp14_;
	const gchar* _tmp15_;
#line 35 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = g_strdup ("Pause Ht");
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (crono_lcd);
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_lcd = _tmp0_;
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->check_jornada = TRUE;
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->tra = FALSE;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp1_ = crono_fconfig;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp2_ = _tmp1_.ruta;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp3_ = g_strconcat (_tmp2_, "gnote-panel.png", NULL);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp4_ = _tmp3_;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp5_ = gtk_status_icon_new_from_file (_tmp4_);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp5_) {
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp5_, "vala-creation-function", "crono.cronotas.init");
#line 277 "cronotas.c"
	}
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (crono_tray_icon);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_tray_icon = _tmp5_;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp4_);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp6_ = crono_tray_icon;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_status_icon_set_visible (_tmp6_, TRUE);
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_create_menu_system (self);
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp7_ = crono_tray_icon;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (_tmp7_, "popup-menu", (GCallback) _crono_cronotas_menu_system_popup_gtk_status_icon_popup_menu, self, 0);
#line 295 "cronotas.c"
	{
		gint i = 0;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		i = 1;
#line 300 "cronotas.c"
		{
			gboolean _tmp8_ = FALSE;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp8_ = TRUE;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			while (TRUE) {
#line 307 "cronotas.c"
				gint _tmp10_;
				gint _tmp11_;
				gint _tmp12_;
				cronotab* _tmp13_;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				if (!_tmp8_) {
#line 314 "cronotas.c"
					gint _tmp9_;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
					_tmp9_ = i;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
					i = _tmp9_ + 1;
#line 320 "cronotas.c"
				}
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				_tmp8_ = FALSE;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				_tmp10_ = i;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				_tmp11_ = crono_max_nota;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				if (!(_tmp10_ <= _tmp11_)) {
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
					break;
#line 332 "cronotas.c"
				}
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				_tmp12_ = i;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				_tmp13_ = crono_tab_new (_tmp12_);
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				if (_tmp13_) {
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
					g_object_set_data ((GObject *) _tmp13_, "vala-creation-function", "crono.cronotas.init");
#line 342 "cronotas.c"
				}
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				g_object_ref_sink (_tmp13_);
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				_g_object_unref0 (self->priv->separar);
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
				self->priv->separar = _tmp13_;
#line 350 "cronotas.c"
			}
		}
	}
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_actualiza_tray (self);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp14_ = crono_fconfig;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp15_ = _tmp14_.color;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_aplicar_color (self, _tmp15_);
#line 362 "cronotas.c"
}


static void
crono_cronotas_menu_system_popup (cronocronotas* self,
                                  guint button,
                                  guint time)
{
	GtkMenu* _tmp0_;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = self->priv->menu_system;
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_popup (_tmp0_, NULL, NULL, NULL, NULL, button, (guint32) time);
#line 378 "cronotas.c"
}


gboolean
crono_cronotas_on_time_trabajo (cronocronotas* self)
{
	gboolean result = FALSE;
	gboolean _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp57_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_val_if_fail (CRONO_IS_CRONOTAS (self), FALSE);
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = self->priv->state_trabajo;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp1_ = self->priv->play;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_ == _tmp1_) {
#line 397 "cronotas.c"
		GtkStatusIcon* _tmp2_;
		cronof_config _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gint _tmp7_;
		gint _tmp8_;
		gint _tmp9_;
		gint _tmp10_;
		gint _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gint _tmp16_;
		gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* _tmp19_;
		gchar* _tmp20_;
		gchar* _tmp21_;
		GtkStatusIcon* _tmp22_;
		gint _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		gchar* _tmp26_;
		gchar* _tmp27_;
		gchar* _tmp28_;
		gchar* _tmp29_;
		gint _tmp30_;
		gchar* _tmp31_;
		gchar* _tmp32_;
		gchar* _tmp33_;
		gchar* _tmp34_;
		gchar* _tmp35_;
		gchar* _tmp36_;
		gint _tmp37_;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp2_ = crono_tray_icon;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp3_ = crono_fconfig;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp4_ = _tmp3_.ruta;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp5_ = g_strconcat (_tmp4_, "gnote-panel.png", NULL);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp6_ = _tmp5_;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_status_icon_set_from_file (_tmp2_, _tmp6_);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp6_);
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->check_jornada = FALSE;
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp7_ = self->priv->ht;
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->ht = _tmp7_ + 1;
#line 57 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp8_ = self->priv->min_trabajo;
#line 57 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->min_trabajo = _tmp8_ + 1;
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp9_ = self->priv->hour_trabajo;
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->hour_trabajo = _tmp9_ + 1;
#line 59 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp10_ = self->priv->min_trabajo;
#line 59 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		if (_tmp10_ == 3600) {
#line 59 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			self->priv->min_trabajo = 0;
#line 468 "cronotas.c"
		}
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp11_ = self->priv->hour_trabajo;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp12_ = crono_formatT (_tmp11_ / 3600);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp13_ = _tmp12_;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp14_ = g_strconcat (_tmp13_, ":", NULL);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp15_ = _tmp14_;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp16_ = self->priv->min_trabajo;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp17_ = crono_formatT (_tmp16_ / 60);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp18_ = _tmp17_;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp19_ = g_strconcat (_tmp15_, _tmp18_, NULL);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp20_ = _tmp19_;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp21_ = g_strconcat (_tmp20_, " Ht", NULL);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (crono_lcd);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		crono_lcd = _tmp21_;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp20_);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp18_);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp15_);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp13_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp22_ = crono_tray_icon;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp23_ = self->priv->hour_trabajo;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp24_ = crono_formatT (_tmp23_ / 3600);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp25_ = _tmp24_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp26_ = g_strconcat ("Tiempo Trabajado - ", _tmp25_, NULL);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp27_ = _tmp26_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp28_ = g_strconcat (_tmp27_, ":", NULL);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp29_ = _tmp28_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp30_ = self->priv->min_trabajo;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp31_ = crono_formatT (_tmp30_ / 60);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp32_ = _tmp31_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp33_ = g_strconcat (_tmp29_, _tmp32_, NULL);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp34_ = _tmp33_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp35_ = g_strconcat (_tmp34_, " ", NULL);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp36_ = _tmp35_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_status_icon_set_tooltip_text (_tmp22_, _tmp36_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp36_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp34_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp32_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp29_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp27_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp25_);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp37_ = self->priv->ht;
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		if (_tmp37_ == 34) {
#line 552 "cronotas.c"
			GtkStatusIcon* _tmp38_;
			cronof_config _tmp39_;
			const gchar* _tmp40_;
			gchar* _tmp41_;
			gchar* _tmp42_;
			gint _tmp43_;
			gint _tmp44_;
			gint _tmp45_;
			gchar* _tmp46_;
			gchar* _tmp47_;
			gchar* _tmp48_;
			gchar* _tmp49_;
			gint _tmp50_;
			gchar* _tmp51_;
			gchar* _tmp52_;
			gchar* _tmp53_;
			gchar* _tmp54_;
			gchar* _tmp55_;
			gchar* _tmp56_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp38_ = crono_tray_icon;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp39_ = crono_fconfig;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp40_ = _tmp39_.ruta;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp41_ = g_strconcat (_tmp40_, "gnote-panel-2.png", NULL);
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp42_ = _tmp41_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			gtk_status_icon_set_from_file (_tmp38_, _tmp42_);
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_g_free0 (_tmp42_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp43_ = self->priv->hour_trabajo;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp44_ = self->priv->min_trabajo;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp45_ = self->priv->hour_trabajo;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp46_ = crono_formatT (_tmp45_ / 3600);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp47_ = _tmp46_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp48_ = g_strconcat (_tmp47_, ":", NULL);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp49_ = _tmp48_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp50_ = self->priv->min_trabajo;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp51_ = crono_formatT (_tmp50_ / 60);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp52_ = _tmp51_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp53_ = g_strconcat (_tmp49_, _tmp52_, NULL);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp54_ = _tmp53_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp55_ = g_strconcat (_tmp54_, " Ht", NULL);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp56_ = _tmp55_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			crono_guarda_trabajo (_tmp43_, _tmp44_, _tmp56_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_g_free0 (_tmp56_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_g_free0 (_tmp54_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_g_free0 (_tmp52_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_g_free0 (_tmp49_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_g_free0 (_tmp47_);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			self->priv->ht = 0;
#line 628 "cronotas.c"
		}
	}
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp57_ = self->priv->state_trabajo;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	result = _tmp57_;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return result;
#line 637 "cronotas.c"
}


static gboolean
_crono_cronotas_on_time_trabajo_gsource_func (gpointer self)
{
	gboolean result;
	result = crono_cronotas_on_time_trabajo ((cronocronotas*) self);
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return result;
#line 648 "cronotas.c"
}


void
crono_cronotas_time_trabajo_play (cronocronotas* self)
{
	gboolean _tmp0_;
	GError * _inner_error_ = NULL;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 71 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = self->priv->check_jornada;
#line 71 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_ == TRUE) {
#line 663 "cronotas.c"
		GtkMenuItem* _tmp1_;
		gboolean _tmp2_;
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp1_ = self->priv->menu_trabajo;
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_menu_item_set_label (_tmp1_, "Pausar Trabajo");
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp2_ = self->priv->play;
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->state_trabajo = _tmp2_;
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->time_trabajo = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _crono_cronotas_on_time_trabajo_gsource_func, g_object_ref (self), g_object_unref);
#line 75 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		crono_cronotas_init_trabajo (self);
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_spawn_command_line_async ("notify-send 'Cronotas!' 'Inicio de Jornada de Trabajo...'", &_inner_error_);
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			g_clear_error (&_inner_error_);
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			return;
#line 688 "cronotas.c"
		}
	} else {
		gboolean _tmp3_;
		GtkMenuItem* _tmp4_;
		gchar* _tmp5_;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp3_ = self->priv->stop;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->state_trabajo = _tmp3_;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp4_ = self->priv->menu_trabajo;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_menu_item_set_label (_tmp4_, "Iniciar Trabajo");
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp5_ = g_strdup (" Pause Ht");
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (crono_lcd);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		crono_lcd = _tmp5_;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		crono_cronotas_actualiza_tray (self);
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->check_jornada = TRUE;
#line 712 "cronotas.c"
	}
}


void
crono_cronotas_actualiza_tray (cronocronotas* self)
{
	GError * _inner_error_ = NULL;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (crono_now_tareas ()) {
#line 725 "cronotas.c"
		GtkStatusIcon* _tmp0_;
		cronof_config _tmp1_;
		const gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GtkStatusIcon* _tmp5_;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp0_ = crono_tray_icon;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp1_ = crono_fconfig;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp2_ = _tmp1_.ruta;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp3_ = g_strconcat (_tmp2_, "gnote-panel-1.png", NULL);
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp4_ = _tmp3_;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_status_icon_set_from_file (_tmp0_, _tmp4_);
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp4_);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp5_ = crono_tray_icon;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_status_icon_set_tooltip_text (_tmp5_, "Tiene Notas Para Hoy...");
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_spawn_command_line_async ("notify-send 'Cronotas!' 'Tiene Notas Pendientes Para Hoy...'", &_inner_error_);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			g_clear_error (&_inner_error_);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			return;
#line 760 "cronotas.c"
		}
	} else {
		GtkStatusIcon* _tmp6_;
		cronof_config _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		GtkStatusIcon* _tmp11_;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp6_ = crono_tray_icon;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp7_ = crono_fconfig;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp8_ = _tmp7_.ruta;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp9_ = g_strconcat (_tmp8_, "gnote-panel.png", NULL);
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp10_ = _tmp9_;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_status_icon_set_from_file (_tmp6_, _tmp10_);
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp10_);
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp11_ = crono_tray_icon;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		gtk_status_icon_set_tooltip_text (_tmp11_, "Cronotas 0.2 - Sin Notas Pendientes");
#line 787 "cronotas.c"
	}
}


static gint
_sqlite3_exec (sqlite3* self,
               const gchar* sql,
               sqlite3_callback callback,
               gpointer callback_target,
               gchar* * errmsg)
{
	gchar* _vala_errmsg = NULL;
	gint result = 0;
	const gchar* sqlite_errmsg = NULL;
	gint ec = 0;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_;
	const gchar* _tmp4_;
#line 34 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 34 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	g_return_val_if_fail (sql != NULL, 0);
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	_tmp1_ = sqlite3_exec (self, sql, callback, callback_target, (char**) (&_tmp0_));
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	sqlite_errmsg = _tmp0_;
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	ec = _tmp1_;
#line 37 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	if ((&_vala_errmsg) != NULL) {
#line 818 "cronotas.c"
		const gchar* _tmp2_;
		gchar* _tmp3_;
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_tmp2_ = sqlite_errmsg;
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_tmp3_ = g_strdup (_tmp2_);
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_g_free0 (_vala_errmsg);
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_vala_errmsg = _tmp3_;
#line 829 "cronotas.c"
	}
#line 40 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	_tmp4_ = sqlite_errmsg;
#line 40 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	sqlite3_free ((void*) _tmp4_);
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	result = ec;
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	if (errmsg) {
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		*errmsg = _vala_errmsg;
#line 841 "cronotas.c"
	} else {
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_g_free0 (_vala_errmsg);
#line 845 "cronotas.c"
	}
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	return result;
#line 849 "cronotas.c"
}


void
crono_cronotas_init_trabajo (cronocronotas* self)
{
	sqlite3_stmt* stmt2 = NULL;
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gchar* errmsg = NULL;
	gchar* mi_fecha = NULL;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GDateTime* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GDateTime* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* query2 = NULL;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	sqlite3* _tmp23_;
	const gchar* _tmp24_;
	sqlite3_stmt* _tmp25_ = NULL;
	gint _tmp26_;
	sqlite3_stmt* _tmp27_;
	sqlite3_stmt* _tmp28_;
	const gchar* _tmp29_;
	gint _tmp30_;
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	now = _tmp0_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp1_ = now;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp2_ = crono_formatT (g_date_time_get_day_of_month (_tmp1_));
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp3_ = _tmp2_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp4_ = g_strconcat (_tmp3_, "/", NULL);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp5_ = _tmp4_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp6_ = now;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp7_ = crono_formatT (g_date_time_get_month (_tmp6_));
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp8_ = _tmp7_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp10_ = _tmp9_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp11_ = g_strconcat (_tmp10_, "/", NULL);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp12_ = _tmp11_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp13_ = now;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp14_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp13_));
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp15_ = _tmp14_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp16_ = g_strconcat (_tmp12_, _tmp15_, NULL);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp17_ = _tmp16_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp15_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp12_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp10_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp8_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp5_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp3_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	mi_fecha = _tmp17_;
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp18_ = mi_fecha;
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp19_ = g_strconcat ("SELECT count(*) from jornada where fecha='", _tmp18_, NULL);
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp20_ = _tmp19_;
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp21_ = g_strconcat (_tmp20_, "';", NULL);
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp22_ = _tmp21_;
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp20_);
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	query2 = _tmp22_;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp23_ = crono_db;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp24_ = query2;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp26_ = sqlite3_prepare_v2 (_tmp23_, _tmp24_, -1, &_tmp25_, NULL);
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_sqlite3_finalize0 (stmt2);
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	stmt2 = _tmp25_;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_rc = _tmp26_;
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp27_ = stmt2;
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	sqlite3_step (_tmp27_);
#line 104 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp28_ = stmt2;
#line 104 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp29_ = sqlite3_column_text (_tmp28_, 0);
#line 104 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->num_jornada = atoi (_tmp29_);
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp30_ = self->priv->num_jornada;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp30_ == 0) {
#line 986 "cronotas.c"
		gchar* _tmp31_;
		gchar* _tmp32_;
		gchar* _tmp33_;
		gchar* _tmp34_;
		gchar* _tmp35_;
		gchar* _tmp36_;
		const gchar* _tmp37_;
		gchar* _tmp38_;
		gchar* _tmp39_;
		gchar* _tmp40_;
		gchar* _tmp41_;
		GDateTime* _tmp42_;
		gchar* _tmp43_;
		gchar* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
		GDateTime* _tmp49_;
		gchar* _tmp50_;
		gchar* _tmp51_;
		gchar* _tmp52_;
		gchar* _tmp53_;
		gchar* _tmp54_;
		sqlite3* _tmp55_;
		const gchar* _tmp56_;
		gchar* _tmp57_ = NULL;
		gint _tmp58_;
		gint _tmp59_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp31_ = g_strdup_printf ("%i", crono_count_jornadas () + 1);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp32_ = _tmp31_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp33_ = g_strconcat ("INSERT INTO jornada (id, fecha, hx,mx,horas,mes,ano) values(", _tmp32_, NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp34_ = _tmp33_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp35_ = g_strconcat (_tmp34_, ",'", NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp36_ = _tmp35_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp37_ = mi_fecha;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp38_ = g_strconcat (_tmp36_, _tmp37_, NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp39_ = _tmp38_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp40_ = g_strconcat (_tmp39_, "',0,0,'00:00 Ht','", NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp41_ = _tmp40_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp42_ = now;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp43_ = crono_formatT (g_date_time_get_month (_tmp42_));
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp44_ = _tmp43_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp45_ = g_strconcat (_tmp41_, _tmp44_, NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp46_ = _tmp45_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp47_ = g_strconcat (_tmp46_, "','", NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp48_ = _tmp47_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp49_ = now;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp50_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp49_));
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp51_ = _tmp50_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp52_ = g_strconcat (_tmp48_, _tmp51_, NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp53_ = _tmp52_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp54_ = g_strconcat (_tmp53_, "');", NULL);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (query2);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		query2 = _tmp54_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp53_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp51_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp48_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp46_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp44_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp41_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp39_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp36_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp34_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp32_);
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp55_ = crono_db;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp56_ = query2;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp58_ = _sqlite3_exec (_tmp55_, _tmp56_, NULL, NULL, &_tmp57_);
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (errmsg);
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		errmsg = _tmp57_;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		crono_rc = _tmp58_;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp59_ = crono_rc;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		if (_tmp59_ != SQLITE_OK) {
#line 1104 "cronotas.c"
			FILE* _tmp60_;
			const gchar* _tmp61_;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp60_ = stderr;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			_tmp61_ = errmsg;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
			fprintf (_tmp60_, "Error: %s\n", _tmp61_);
#line 1113 "cronotas.c"
		}
	} else {
		const gchar* _tmp62_;
		gchar* _tmp63_;
		gchar* _tmp64_;
		gchar* _tmp65_;
		sqlite3* _tmp66_;
		const gchar* _tmp67_;
		sqlite3_stmt* _tmp68_ = NULL;
		sqlite3_stmt* _tmp69_;
		sqlite3_stmt* _tmp70_;
		const gchar* _tmp71_;
		sqlite3_stmt* _tmp72_;
		const gchar* _tmp73_;
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp62_ = mi_fecha;
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp63_ = g_strconcat ("SELECT * from jornada where fecha='", _tmp62_, NULL);
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp64_ = _tmp63_;
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp65_ = g_strconcat (_tmp64_, "';", NULL);
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (query2);
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		query2 = _tmp65_;
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_free0 (_tmp64_);
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp66_ = crono_db;
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp67_ = query2;
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		sqlite3_prepare_v2 (_tmp66_, _tmp67_, -1, &_tmp68_, NULL);
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_sqlite3_finalize0 (stmt2);
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		stmt2 = _tmp68_;
#line 114 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp69_ = stmt2;
#line 114 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		sqlite3_step (_tmp69_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp70_ = stmt2;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp71_ = sqlite3_column_text (_tmp70_, 3);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->min_trabajo = atoi (_tmp71_);
#line 116 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp72_ = stmt2;
#line 116 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_tmp73_ = sqlite3_column_text (_tmp72_, 2);
#line 116 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		self->priv->hour_trabajo = atoi (_tmp73_);
#line 1168 "cronotas.c"
	}
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (query2);
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (mi_fecha);
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (errmsg);
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_date_time_unref0 (now);
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_sqlite3_finalize0 (stmt2);
#line 1180 "cronotas.c"
}


static void
__lambda6_ (cronocronotas* self)
{
	cronotab* _tmp0_;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = crono_tab_new (crono_crear_ficha ());
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.create_menu_system._lambda6_");
#line 1194 "cronotas.c"
	}
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->separar);
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->separar = _tmp0_;
#line 1202 "cronotas.c"
}


static void
___lambda6__gtk_menu_item_activate (GtkMenuItem* _sender,
                                    gpointer self)
{
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	__lambda6_ ((cronocronotas*) self);
#line 1212 "cronotas.c"
}


static void
__lambda7_ (cronocronotas* self)
{
	cronotempo* _tmp0_;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = crono_tempo_new ();
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.create_menu_system._lambda7_");
#line 1226 "cronotas.c"
	}
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->temporizador);
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->temporizador = _tmp0_;
#line 1234 "cronotas.c"
}


static void
___lambda7__gtk_menu_item_activate (GtkMenuItem* _sender,
                                    gpointer self)
{
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	__lambda7_ ((cronocronotas*) self);
#line 1244 "cronotas.c"
}


static void
_crono_cronotas_time_trabajo_play_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                          gpointer self)
{
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_time_trabajo_play ((cronocronotas*) self);
#line 1254 "cronotas.c"
}


static void
__lambda8_ (cronocronotas* self)
{
	cronodialog_jornada* _tmp0_;
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = crono_dialog_jornada_new ();
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.create_menu_system._lambda8_");
#line 1268 "cronotas.c"
	}
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->jornadas);
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->jornadas = _tmp0_;
#line 1276 "cronotas.c"
}


static void
___lambda8__gtk_menu_item_activate (GtkMenuItem* _sender,
                                    gpointer self)
{
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	__lambda8_ ((cronocronotas*) self);
#line 1286 "cronotas.c"
}


static void
__lambda9_ (cronocronotas* self)
{
	cronoconfig* _tmp0_;
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = crono_config_new ();
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.create_menu_system._lambda9_");
#line 1300 "cronotas.c"
	}
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->dialog_config);
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->dialog_config = _tmp0_;
#line 1308 "cronotas.c"
}


static void
___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender,
                                    gpointer self)
{
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	__lambda9_ ((cronocronotas*) self);
#line 1318 "cronotas.c"
}


static void
_crono_cronotas_about_clicked_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                      gpointer self)
{
#line 141 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_about_clicked ((cronocronotas*) self);
#line 1328 "cronotas.c"
}


static void
_gtk_main_quit_gtk_menu_item_activate (GtkMenuItem* _sender,
                                       gpointer self)
{
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_main_quit ();
#line 1338 "cronotas.c"
}


void
crono_cronotas_create_menu_system (cronocronotas* self)
{
	GtkMenu* _tmp0_;
	GtkImageMenuItem* menu_nueva = NULL;
	GtkImageMenuItem* _tmp1_;
	GtkMenu* _tmp2_;
	GtkMenuItem* menu_tempo = NULL;
	GtkMenuItem* _tmp3_;
	GtkMenu* _tmp4_;
	GtkSeparatorMenuItem* separator1 = NULL;
	GtkSeparatorMenuItem* _tmp5_;
	GtkMenu* _tmp6_;
	GtkMenuItem* _tmp7_;
	GtkMenuItem* _tmp8_;
	GtkMenu* _tmp9_;
	GtkMenuItem* _tmp10_;
	GtkMenuItem* menu_jornada = NULL;
	GtkMenuItem* _tmp11_;
	GtkMenu* _tmp12_;
	GtkMenuItem* menu_config = NULL;
	GtkMenuItem* _tmp13_;
	GtkMenu* _tmp14_;
	GtkSeparatorMenuItem* separator2 = NULL;
	GtkSeparatorMenuItem* _tmp15_;
	GtkMenu* _tmp16_;
	GtkImageMenuItem* menu_about = NULL;
	GtkImageMenuItem* _tmp17_;
	GtkMenu* _tmp18_;
	GtkImageMenuItem* menu_quit = NULL;
	GtkImageMenuItem* _tmp19_;
	GtkMenu* _tmp20_;
	GtkMenu* _tmp21_;
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = (GtkMenu*) gtk_menu_new ();
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1383 "cronotas.c"
	}
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->menu_system);
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->menu_system = _tmp0_;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp1_ = (GtkImageMenuItem*) gtk_image_menu_item_new_from_stock (GTK_STOCK_NEW, NULL);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp1_) {
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp1_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1397 "cronotas.c"
	}
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp1_);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	menu_nueva = _tmp1_;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (menu_nueva, gtk_menu_item_get_type (), GtkMenuItem), "activate", (GCallback) ___lambda6__gtk_menu_item_activate, self, 0);
#line 123 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp2_ = self->priv->menu_system;
#line 123 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_menu_shell_get_type (), GtkMenuShell), G_TYPE_CHECK_INSTANCE_CAST (menu_nueva, gtk_menu_item_get_type (), GtkMenuItem));
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp3_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Temporizador");
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp3_) {
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp3_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1415 "cronotas.c"
	}
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp3_);
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	menu_tempo = _tmp3_;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (menu_tempo, "activate", (GCallback) ___lambda7__gtk_menu_item_activate, self, 0);
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp4_ = self->priv->menu_system;
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, gtk_menu_shell_get_type (), GtkMenuShell), menu_tempo);
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp5_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp5_) {
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp5_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1433 "cronotas.c"
	}
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp5_);
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	separator1 = _tmp5_;
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp6_ = self->priv->menu_system;
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, gtk_menu_shell_get_type (), GtkMenuShell), G_TYPE_CHECK_INSTANCE_CAST (separator1, gtk_menu_item_get_type (), GtkMenuItem));
#line 129 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp7_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Iniciar Trabajo");
#line 129 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp7_) {
#line 129 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp7_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1449 "cronotas.c"
	}
#line 129 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp7_);
#line 129 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->menu_trabajo);
#line 129 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->menu_trabajo = _tmp7_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp8_ = self->priv->menu_trabajo;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (_tmp8_, "activate", (GCallback) _crono_cronotas_time_trabajo_play_gtk_menu_item_activate, self, 0);
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp9_ = self->priv->menu_system;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp10_ = self->priv->menu_trabajo;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, gtk_menu_shell_get_type (), GtkMenuShell), _tmp10_);
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp11_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Reporte de Jornadas");
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp11_) {
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp11_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1473 "cronotas.c"
	}
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp11_);
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	menu_jornada = _tmp11_;
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (menu_jornada, "activate", (GCallback) ___lambda8__gtk_menu_item_activate, self, 0);
#line 134 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp12_ = self->priv->menu_system;
#line 134 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp12_, gtk_menu_shell_get_type (), GtkMenuShell), menu_jornada);
#line 135 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp13_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Configuración");
#line 135 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp13_) {
#line 135 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp13_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1491 "cronotas.c"
	}
#line 135 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp13_);
#line 135 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	menu_config = _tmp13_;
#line 136 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (menu_config, "activate", (GCallback) ___lambda9__gtk_menu_item_activate, self, 0);
#line 137 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp14_ = self->priv->menu_system;
#line 137 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp14_, gtk_menu_shell_get_type (), GtkMenuShell), menu_config);
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp15_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp15_) {
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp15_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1509 "cronotas.c"
	}
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp15_);
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	separator2 = _tmp15_;
#line 139 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp16_ = self->priv->menu_system;
#line 139 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, gtk_menu_shell_get_type (), GtkMenuShell), G_TYPE_CHECK_INSTANCE_CAST (separator2, gtk_menu_item_get_type (), GtkMenuItem));
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp17_ = (GtkImageMenuItem*) gtk_image_menu_item_new_from_stock (GTK_STOCK_ABOUT, NULL);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp17_) {
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp17_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1525 "cronotas.c"
	}
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp17_);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	menu_about = _tmp17_;
#line 141 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (menu_about, gtk_menu_item_get_type (), GtkMenuItem), "activate", (GCallback) _crono_cronotas_about_clicked_gtk_menu_item_activate, self, 0);
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp18_ = self->priv->menu_system;
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp18_, gtk_menu_shell_get_type (), GtkMenuShell), G_TYPE_CHECK_INSTANCE_CAST (menu_about, gtk_menu_item_get_type (), GtkMenuItem));
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp19_ = (GtkImageMenuItem*) gtk_image_menu_item_new_from_stock (GTK_STOCK_QUIT, NULL);
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp19_) {
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp19_, "vala-creation-function", "crono.cronotas.create_menu_system");
#line 1543 "cronotas.c"
	}
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp19_);
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	menu_quit = _tmp19_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_signal_connect (G_TYPE_CHECK_INSTANCE_CAST (menu_quit, gtk_menu_item_get_type (), GtkMenuItem), "activate", (GCallback) _gtk_main_quit_gtk_menu_item_activate, NULL);
#line 145 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp20_ = self->priv->menu_system;
#line 145 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_menu_shell_append (G_TYPE_CHECK_INSTANCE_CAST (_tmp20_, gtk_menu_shell_get_type (), GtkMenuShell), G_TYPE_CHECK_INSTANCE_CAST (menu_quit, gtk_menu_item_get_type (), GtkMenuItem));
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp21_ = self->priv->menu_system;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_widget_show_all (G_TYPE_CHECK_INSTANCE_CAST (_tmp21_, gtk_widget_get_type (), GtkWidget));
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (menu_quit);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (menu_about);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (separator2);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (menu_config);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (menu_jornada);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (separator1);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (menu_tempo);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (menu_nueva);
#line 1575 "cronotas.c"
}


static void
crono_cronotas_about_clicked (cronocronotas* self)
{
	GtkAboutDialog* about = NULL;
	GtkAboutDialog* _tmp0_;
	GdkPixbuf* _tmp1_ = NULL;
	cronof_config _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GdkPixbuf* _tmp6_;
	GdkPixbuf* _tmp7_;
	GError * _inner_error_ = NULL;
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = (GtkAboutDialog*) gtk_about_dialog_new ();
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.about_clicked");
#line 1600 "cronotas.c"
	}
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	about = _tmp0_;
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp2_ = crono_fconfig;
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp3_ = _tmp2_.ruta;
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp4_ = g_strconcat (_tmp3_, "notes-app.png", NULL);
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp5_ = _tmp4_;
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp6_ = gdk_pixbuf_new_from_file (_tmp5_, &_inner_error_);
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp6_) {
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp6_, "vala-creation-function", "crono.cronotas.about_clicked");
#line 1620 "cronotas.c"
	}
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp7_ = _tmp6_;
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp5_);
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp1_ = _tmp7_;
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_object_unref0 (about);
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_clear_error (&_inner_error_);
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		return;
#line 1638 "cronotas.c"
	}
#line 150 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_logo (about, _tmp1_);
#line 151 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_website (about, "http://www.didapax.com.ve");
#line 152 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_website_label (about, "Didapax Sistem");
#line 153 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_version (about, "0.2.1");
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_program_name (about, "Cronotas");
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_comments (about, "Cronometros y Notas al mismo Tiempo");
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_about_dialog_set_copyright (about, "Daniel Alfonsi -Didapax- (c)2018 ");
#line 157 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_dialog_run (G_TYPE_CHECK_INSTANCE_CAST (about, gtk_dialog_get_type (), GtkDialog));
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_widget_hide (G_TYPE_CHECK_INSTANCE_CAST (about, gtk_widget_get_type (), GtkWidget));
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (_tmp1_);
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (about);
#line 1662 "cronotas.c"
}


gint
crono_cronotas_main (gchar** args,
                     int args_length1)
{
	gint result = 0;
	cronocronotas* app = NULL;
	cronocronotas* _tmp0_;
#line 161 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_init (&args_length1, &args);
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = crono_cronotas_new ();
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp0_) {
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.cronotas.main");
#line 1681 "cronotas.c"
	}
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_object_ref_sink (_tmp0_);
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	app = _tmp0_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_main ();
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	result = 0;
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (app);
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return result;
#line 1695 "cronotas.c"
}


int
main (int argc,
      char ** argv)
{
#line 160 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return crono_cronotas_main (argv, argc);
#line 1705 "cronotas.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	return self ? g_object_ref (self) : NULL;
#line 1714 "cronotas.c"
}


void
crono_cronotas_aplicar_color (cronocronotas* self,
                              const gchar* color)
{
	GdkScreen* screen = NULL;
	GdkScreen* _tmp0_;
	GdkScreen* _tmp1_;
	GtkCssProvider* css_provider = NULL;
	GtkCssProvider* _tmp2_;
	cronof_config _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GtkStyleContext* style_context = NULL;
	GtkStyleContext* _tmp9_;
	GtkStyleContext* _tmp10_;
	GtkStyleContext* _tmp11_;
	GError * _inner_error_ = NULL;
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (CRONO_IS_CRONOTAS (self));
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_return_if_fail (color != NULL);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp0_ = gdk_screen_get_default ();
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	screen = _tmp1_;
#line 168 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp2_ = gtk_css_provider_new ();
#line 168 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (_tmp2_) {
#line 168 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_object_set_data ((GObject *) _tmp2_, "vala-creation-function", "crono.cronotas.aplicar_color");
#line 1754 "cronotas.c"
	}
#line 168 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	css_provider = _tmp2_;
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp3_ = crono_fconfig;
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp4_ = _tmp3_.ruta;
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp5_ = g_strconcat (_tmp4_, color, NULL);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp6_ = _tmp5_;
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp7_ = g_strconcat (_tmp6_, ".css", NULL);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp8_ = _tmp7_;
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_css_provider_load_from_path (css_provider, _tmp8_, &_inner_error_);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp8_);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_free0 (_tmp6_);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_object_unref0 (css_provider);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		_g_object_unref0 (screen);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		g_clear_error (&_inner_error_);
#line 169 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
		return;
#line 1788 "cronotas.c"
	}
#line 170 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp9_ = gtk_widget_get_style_context (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_widget_get_type (), GtkWidget));
#line 170 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp10_ = _g_object_ref0 (_tmp9_);
#line 170 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	style_context = _tmp10_;
#line 171 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_tmp11_ = style_context;
#line 171 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	gtk_style_context_add_provider_for_screen (screen, G_TYPE_CHECK_INSTANCE_CAST (css_provider, gtk_style_provider_get_type (), GtkStyleProvider), (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (style_context);
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (css_provider);
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (screen);
#line 1806 "cronotas.c"
}


static void
crono_cronotas_class_init (cronocronotasClass * klass)
{
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	crono_cronotas_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	g_type_class_add_private (klass, sizeof (cronocronotasPrivate));
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	G_OBJECT_CLASS (klass)->finalize = crono_cronotas_finalize;
#line 1819 "cronotas.c"
}


static void
crono_cronotas_instance_init (cronocronotas * self)
{
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv = CRONO_CRONOTAS_GET_PRIVATE (self);
#line 28 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->play = TRUE;
#line 29 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self->priv->stop = FALSE;
#line 1832 "cronotas.c"
}


static void
crono_cronotas_finalize (GObject * obj)
{
	cronocronotas * self;
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CRONO_TYPE_CRONOTAS, cronocronotas);
#line 15 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->separar);
#line 16 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->menu_system);
#line 17 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->jornadas);
#line 18 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->temporizador);
#line 19 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->dialog_config);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	_g_object_unref0 (self->priv->menu_trabajo);
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/cronotas.vala"
	G_OBJECT_CLASS (crono_cronotas_parent_class)->finalize (obj);
#line 1856 "cronotas.c"
}


GType
crono_cronotas_get_type (void)
{
	static volatile gsize crono_cronotas_type_id__volatile = 0;
	if (g_once_init_enter (&crono_cronotas_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (cronocronotasClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) crono_cronotas_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (cronocronotas), 0, (GInstanceInitFunc) crono_cronotas_instance_init, NULL };
		GType crono_cronotas_type_id;
		crono_cronotas_type_id = g_type_register_static (gtk_window_get_type (), "cronocronotas", &g_define_type_info, 0);
		g_once_init_leave (&crono_cronotas_type_id__volatile, crono_cronotas_type_id);
	}
	return crono_cronotas_type_id__volatile;
}



