/* database.c generated by valac 0.40.8, the Vala compiler
 * generated from database.vala, do not modify */

/*
Cronotas (c) Didapax Sistem Daniel Alfonsi 
2019
*/


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <sqlite3.h>
#include <stdio.h>


#define CRONO_TYPE_F_NOTAS (crono_f_notas_get_type ())
typedef struct _cronof_notas cronof_notas;
#define _g_free0(var) (var = (g_free (var), NULL))

#define CRONO_TYPE_F_CONFIG (crono_f_config_get_type ())
typedef struct _cronof_config cronof_config;
#define _sqlite3_close0(var) ((var == NULL) ? NULL : (var = (sqlite3_close (var), NULL)))
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _cronof_notas {
	gchar* id;
	gchar* fecha;
	gchar* nombre;
	gchar* nota;
	gint proteger;
	gint completar;
	gchar* color;
	gboolean visible;
};

struct _cronof_config {
	gchar* id;
	gchar* ruta;
	gchar* color;
};


extern cronof_config crono_fconfig;
cronof_config crono_fconfig = {0};
extern cronof_notas crono_ficha[100];
cronof_notas crono_ficha[100] = {0};
extern gint crono_max_nota;
gint crono_max_nota = 0;
extern gint crono_rc;
gint crono_rc = 0;
extern sqlite3* crono_db;
sqlite3* crono_db = NULL;
extern sqlite3* crono_db_config;
sqlite3* crono_db_config = NULL;
extern sqlite3_stmt* crono_stmt;
sqlite3_stmt* crono_stmt = NULL;
extern sqlite3_stmt* crono_stmt_config;
sqlite3_stmt* crono_stmt_config = NULL;

GType crono_f_notas_get_type (void) G_GNUC_CONST;
cronof_notas* crono_f_notas_dup (const cronof_notas* self);
void crono_f_notas_free (cronof_notas* self);
void crono_f_notas_copy (const cronof_notas* self,
                         cronof_notas* dest);
void crono_f_notas_destroy (cronof_notas* self);
GType crono_f_config_get_type (void) G_GNUC_CONST;
cronof_config* crono_f_config_dup (const cronof_config* self);
void crono_f_config_free (cronof_config* self);
void crono_f_config_copy (const cronof_config* self,
                          cronof_config* dest);
void crono_f_config_destroy (cronof_config* self);
void crono_init_datos (void);
void crono_create_config (void);
void crono_create_tables (void);
void crono_llenarFichas (void);
gboolean crono_if_config (void);
gchar* crono_formatT (gint valor);
gint crono_max_id (void);
gint crono_crear_ficha (void);
void crono_guardar (const gchar* nombre,
                    const gchar* nota,
                    const gchar* color,
                    const gchar* id);
gint crono_count_jornadas (void);
void crono_guarda_trabajo (gint hx,
                           gint mx,
                           const gchar* lcd);
gboolean crono_if_tareas_hoy (gint id);
gboolean crono_now_tareas (void);


void
crono_f_notas_copy (const cronof_notas* self,
                    cronof_notas* dest)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gboolean _tmp12_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = (*self).id;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).id);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).id = _tmp1_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = (*self).fecha;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).fecha);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).fecha = _tmp3_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = (*self).nombre;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).nombre);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).nombre = _tmp5_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = (*self).nota;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = g_strdup (_tmp6_);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).nota);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).nota = _tmp7_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = (*self).proteger;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).proteger = _tmp8_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = (*self).completar;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).completar = _tmp9_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = (*self).color;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = g_strdup (_tmp10_);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).color);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).color = _tmp11_;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = (*self).visible;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).visible = _tmp12_;
#line 165 "database.c"
}


void
crono_f_notas_destroy (cronof_notas* self)
{
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).id);
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).fecha);
#line 13 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).nombre);
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).nota);
#line 17 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).color);
#line 182 "database.c"
}


cronof_notas*
crono_f_notas_dup (const cronof_notas* self)
{
	cronof_notas* dup;
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	dup = g_new0 (cronof_notas, 1);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_f_notas_copy (self, dup);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	return dup;
#line 196 "database.c"
}


void
crono_f_notas_free (cronof_notas* self)
{
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_f_notas_destroy (self);
#line 10 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_free (self);
#line 207 "database.c"
}


GType
crono_f_notas_get_type (void)
{
	static volatile gsize crono_f_notas_type_id__volatile = 0;
	if (g_once_init_enter (&crono_f_notas_type_id__volatile)) {
		GType crono_f_notas_type_id;
		crono_f_notas_type_id = g_boxed_type_register_static ("cronof_notas", (GBoxedCopyFunc) crono_f_notas_dup, (GBoxedFreeFunc) crono_f_notas_free);
		g_once_init_leave (&crono_f_notas_type_id__volatile, crono_f_notas_type_id);
	}
	return crono_f_notas_type_id__volatile;
}


void
crono_f_config_copy (const cronof_config* self,
                     cronof_config* dest)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = (*self).id;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).id);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).id = _tmp1_;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = (*self).ruta;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).ruta);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).ruta = _tmp3_;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = (*self).color;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*dest).color);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	(*dest).color = _tmp5_;
#line 258 "database.c"
}


void
crono_f_config_destroy (cronof_config* self)
{
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).id);
#line 22 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).ruta);
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 ((*self).color);
#line 271 "database.c"
}


cronof_config*
crono_f_config_dup (const cronof_config* self)
{
	cronof_config* dup;
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	dup = g_new0 (cronof_config, 1);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_f_config_copy (self, dup);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	return dup;
#line 285 "database.c"
}


void
crono_f_config_free (cronof_config* self)
{
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_f_config_destroy (self);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_free (self);
#line 296 "database.c"
}


GType
crono_f_config_get_type (void)
{
	static volatile gsize crono_f_config_type_id__volatile = 0;
	if (g_once_init_enter (&crono_f_config_type_id__volatile)) {
		GType crono_f_config_type_id;
		crono_f_config_type_id = g_boxed_type_register_static ("cronof_config", (GBoxedCopyFunc) crono_f_config_dup, (GBoxedFreeFunc) crono_f_config_free);
		g_once_init_leave (&crono_f_config_type_id__volatile, crono_f_config_type_id);
	}
	return crono_f_config_type_id__volatile;
}


void
crono_init_datos (void)
{
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_create_config ();
#line 35 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_create_tables ();
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_llenarFichas ();
#line 322 "database.c"
}


static gint
_sqlite3_exec (sqlite3* self,
               const gchar* sql,
               sqlite3_callback callback,
               gpointer callback_target,
               gchar* * errmsg)
{
	gchar* _vala_errmsg = NULL;
	gint result = 0;
	const gchar* sqlite_errmsg = NULL;
	gint ec = 0;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_;
	const gchar* _tmp4_;
#line 34 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 34 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	g_return_val_if_fail (sql != NULL, 0);
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	_tmp1_ = sqlite3_exec (self, sql, callback, callback_target, (char**) (&_tmp0_));
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	sqlite_errmsg = _tmp0_;
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	ec = _tmp1_;
#line 37 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	if ((&_vala_errmsg) != NULL) {
#line 352 "database.c"
		const gchar* _tmp2_;
		gchar* _tmp3_;
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_tmp2_ = sqlite_errmsg;
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_tmp3_ = g_strdup (_tmp2_);
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_g_free0 (_vala_errmsg);
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_vala_errmsg = _tmp3_;
#line 363 "database.c"
	}
#line 40 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	_tmp4_ = sqlite_errmsg;
#line 40 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	sqlite3_free ((void*) _tmp4_);
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	result = ec;
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	if (errmsg) {
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		*errmsg = _vala_errmsg;
#line 375 "database.c"
	} else {
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_g_free0 (_vala_errmsg);
#line 379 "database.c"
	}
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	return result;
#line 383 "database.c"
}


void
crono_create_tables (void)
{
	gchar* errmsg = NULL;
	cronof_config _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	sqlite3* _tmp4_ = NULL;
	gint _tmp5_;
	gchar* query = NULL;
	gchar* _tmp6_;
	sqlite3* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_ = NULL;
	gint _tmp10_;
	gchar* _tmp11_;
	sqlite3* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_ = NULL;
	gint _tmp15_;
	gchar* _tmp16_;
	sqlite3* _tmp17_;
	const gchar* _tmp18_;
	sqlite3_stmt* _tmp19_ = NULL;
	sqlite3_stmt* _tmp20_;
	sqlite3_stmt* _tmp21_;
	const gchar* _tmp22_;
	gint _tmp23_;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = crono_fconfig;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = _tmp0_.ruta;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = g_strconcat (_tmp1_, "notas.db", NULL);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = _tmp2_;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = sqlite3_open (_tmp3_, &_tmp4_);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_close0 (crono_db);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_db = _tmp4_;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp5_;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp3_);
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = g_strdup ("CREATE TABLE IF NOT EXISTS nota (id INT PRIMARY KEY NOT NULL,fecha DAT" \
"E,nombre TEXT,nota TEXT,proteger INT,completar INT,color TEXT, pcolor " \
"TEXT);");
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp6_;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = crono_db;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = query;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = _sqlite3_exec (_tmp7_, _tmp8_, NULL, NULL, &_tmp9_);
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	errmsg = _tmp9_;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp10_;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = g_strdup ("CREATE TABLE IF NOT EXISTS jornada (id INT PRIMARY KEY NOT NULL,fecha " \
"DATE,hx INT,mx INT,horas TEXT,mes TEXT,ano TEXT);");
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp11_;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = crono_db;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp13_ = query;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp15_ = _sqlite3_exec (_tmp12_, _tmp13_, NULL, NULL, &_tmp14_);
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	errmsg = _tmp14_;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp15_;
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp16_ = g_strdup ("SELECT count(*) from nota;");
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp16_;
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp17_ = crono_db;
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp18_ = query;
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_prepare_v2 (_tmp17_, _tmp18_, -1, &_tmp19_, NULL);
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (crono_stmt);
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_stmt = _tmp19_;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = crono_stmt;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (_tmp20_);
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp21_ = crono_stmt;
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp22_ = sqlite3_column_text (_tmp21_, 0);
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_max_nota = atoi (_tmp22_);
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp23_ = crono_rc;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (_tmp23_ != SQLITE_OK) {
#line 498 "database.c"
		FILE* _tmp24_;
		const gchar* _tmp25_;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp24_ = stderr;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp25_ = errmsg;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		fprintf (_tmp24_, "Error: %s\n", _tmp25_);
#line 507 "database.c"
	} else {
		gint _tmp26_;
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp26_ = crono_max_nota;
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		if (_tmp26_ == 0) {
#line 514 "database.c"
			gint _tmp27_;
			gchar* _tmp28_;
			gchar* _tmp29_;
			gchar* _tmp30_;
			gchar* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			gint _tmp34_;
			gchar* _tmp35_;
			gchar* _tmp36_;
			gchar* _tmp37_;
			gchar* _tmp38_;
			gchar* _tmp39_;
			sqlite3* _tmp40_;
			const gchar* _tmp41_;
			gchar* _tmp42_ = NULL;
			gint _tmp43_;
			gint _tmp44_;
#line 51 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			g_print ("No hay datos\n");
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp27_ = crono_max_nota;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp28_ = g_strdup_printf ("%i", _tmp27_ + 1);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp29_ = _tmp28_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp30_ = g_strconcat ("INSERT INTO nota (id,fecha,nombre,nota,proteger,completar,color) value" \
"s(", _tmp29_, NULL);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp31_ = _tmp30_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp32_ = g_strconcat (_tmp31_, ",'00/00/0000','Nota", NULL);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp33_ = _tmp32_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp34_ = crono_max_nota;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp35_ = g_strdup_printf ("%i", _tmp34_ + 1);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp36_ = _tmp35_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp37_ = g_strconcat (_tmp33_, _tmp36_, NULL);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp38_ = _tmp37_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp39_ = g_strconcat (_tmp38_, "','',0,0,'amarillo.css');", NULL);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (query);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			query = _tmp39_;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (_tmp38_);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (_tmp36_);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (_tmp33_);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (_tmp31_);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (_tmp29_);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp40_ = crono_db;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp41_ = query;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp43_ = _sqlite3_exec (_tmp40_, _tmp41_, NULL, NULL, &_tmp42_);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_g_free0 (errmsg);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			errmsg = _tmp42_;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			crono_rc = _tmp43_;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp44_ = crono_rc;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			if (_tmp44_ == SQLITE_OK) {
#line 591 "database.c"
				gint _tmp45_;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp45_ = crono_max_nota;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_max_nota = _tmp45_ + 1;
#line 597 "database.c"
			} else {
				const gchar* _tmp46_;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp46_ = errmsg;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				g_print ("Error: %s", _tmp46_);
#line 604 "database.c"
			}
		}
	}
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 612 "database.c"
}


void
crono_create_config (void)
{
	gchar* errmsg = NULL;
	sqlite3_stmt* stmt_config = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	sqlite3* _tmp3_ = NULL;
	gint _tmp4_;
	gchar* query = NULL;
	gchar* _tmp5_;
	sqlite3* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_ = NULL;
	gint _tmp9_;
	gchar* _tmp20_;
	sqlite3* _tmp21_;
	const gchar* _tmp22_;
	sqlite3_stmt* _tmp23_ = NULL;
	gint _tmp24_;
	const gchar* _tmp25_;
	gchar* _tmp26_;
	const gchar* _tmp27_;
	gchar* _tmp28_;
	const gchar* _tmp29_;
	gchar* _tmp30_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_get_home_dir ();
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/.cronotas/config.db", NULL);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = _tmp1_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = sqlite3_open (_tmp2_, &_tmp3_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_close0 (crono_db_config);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_db_config = _tmp3_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp4_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp2_);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = g_strdup ("CREATE TABLE IF NOT EXISTS config (id INT PRIMARY KEY NOT NULL,ruta TE" \
"XT, color TEXT);");
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp5_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = crono_db_config;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = query;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = _sqlite3_exec (_tmp6_, _tmp7_, NULL, NULL, &_tmp8_);
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	errmsg = _tmp8_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp9_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (!crono_if_config ()) {
#line 677 "database.c"
		const gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		sqlite3* _tmp14_;
		const gchar* _tmp15_;
		gchar* _tmp16_ = NULL;
		gint _tmp17_;
		gint _tmp18_;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp10_ = g_get_home_dir ();
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp11_ = g_strconcat ("INSERT INTO config (id,ruta,color) values(0,'", _tmp10_, NULL);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp12_ = _tmp11_;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp13_ = g_strconcat (_tmp12_, "/.cronotas/','amarillo');", NULL);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		query = _tmp13_;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (_tmp12_);
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp14_ = crono_db_config;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp15_ = query;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp17_ = _sqlite3_exec (_tmp14_, _tmp15_, NULL, NULL, &_tmp16_);
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (errmsg);
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		errmsg = _tmp16_;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		crono_rc = _tmp17_;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp18_ = crono_rc;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		if (_tmp18_ != SQLITE_OK) {
#line 717 "database.c"
			const gchar* _tmp19_;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp19_ = errmsg;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			g_print ("Error: %s\n", _tmp19_);
#line 723 "database.c"
		}
	}
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = g_strdup ("SELECT * from config;");
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp20_;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp21_ = crono_db_config;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp22_ = query;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp24_ = sqlite3_prepare_v2 (_tmp21_, _tmp22_, -1, &_tmp23_, NULL);
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_config);
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	stmt_config = _tmp23_;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp24_;
#line 71 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (stmt_config);
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp25_ = sqlite3_column_text (stmt_config, 0);
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp26_ = g_strdup (_tmp25_);
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_fconfig.id);
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_fconfig.id = _tmp26_;
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp27_ = sqlite3_column_text (stmt_config, 1);
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp28_ = g_strdup (_tmp27_);
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_fconfig.ruta);
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_fconfig.ruta = _tmp28_;
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp29_ = sqlite3_column_text (stmt_config, 2);
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp30_ = g_strdup (_tmp29_);
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_fconfig.color);
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_fconfig.color = _tmp30_;
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_config);
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 776 "database.c"
}


gboolean
crono_if_config (void)
{
	gboolean result = FALSE;
	sqlite3_stmt* stmt_config = NULL;
	gchar* query = NULL;
	gchar* _tmp0_;
	sqlite3* _tmp1_;
	const gchar* _tmp2_;
	sqlite3_stmt* _tmp3_ = NULL;
	gint _tmp4_;
	sqlite3_stmt* _tmp5_;
	sqlite3_stmt* _tmp6_;
	const gchar* _tmp7_;
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_strdup ("SELECT COUNT(*)  from config;");
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp0_;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = crono_db_config;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = query;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = sqlite3_prepare_v2 (_tmp1_, _tmp2_, -1, &_tmp3_, NULL);
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_config);
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	stmt_config = _tmp3_;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp4_;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = stmt_config;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (_tmp5_);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = stmt_config;
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = sqlite3_column_text (_tmp6_, 0);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (atoi (_tmp7_) > 0) {
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		result = TRUE;
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_sqlite3_finalize0 (stmt_config);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		return result;
#line 828 "database.c"
	} else {
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		result = FALSE;
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_sqlite3_finalize0 (stmt_config);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		return result;
#line 838 "database.c"
	}
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_config);
#line 844 "database.c"
}


void
crono_llenarFichas (void)
{
	gchar* query = NULL;
	gchar* _tmp0_;
	sqlite3* _tmp1_;
	const gchar* _tmp2_;
	sqlite3_stmt* _tmp3_ = NULL;
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_strdup ("select * from nota order by fecha desc;");
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp0_;
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = crono_db;
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = query;
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_prepare_v2 (_tmp1_, _tmp2_, -1, &_tmp3_, NULL);
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (crono_stmt);
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_stmt = _tmp3_;
#line 870 "database.c"
	{
		gint i = 0;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		i = 1;
#line 875 "database.c"
		{
			gboolean _tmp4_ = FALSE;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			_tmp4_ = TRUE;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
			while (TRUE) {
#line 882 "database.c"
				gint _tmp6_;
				gint _tmp7_;
				sqlite3_stmt* _tmp8_;
				gint _tmp9_;
				sqlite3_stmt* _tmp10_;
				const gchar* _tmp11_;
				gchar* _tmp12_;
				gint _tmp13_;
				sqlite3_stmt* _tmp14_;
				const gchar* _tmp15_;
				gchar* _tmp16_;
				gint _tmp17_;
				sqlite3_stmt* _tmp18_;
				const gchar* _tmp19_;
				gchar* _tmp20_;
				gint _tmp21_;
				sqlite3_stmt* _tmp22_;
				const gchar* _tmp23_;
				gchar* _tmp24_;
				gint _tmp25_;
				sqlite3_stmt* _tmp26_;
				gint _tmp27_;
				sqlite3_stmt* _tmp28_;
				gint _tmp29_;
				sqlite3_stmt* _tmp30_;
				const gchar* _tmp31_;
				gchar* _tmp32_;
				gint _tmp33_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				if (!_tmp4_) {
#line 913 "database.c"
					gint _tmp5_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
					_tmp5_ = i;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
					i = _tmp5_ + 1;
#line 919 "database.c"
				}
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp4_ = FALSE;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp6_ = i;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp7_ = crono_max_nota;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				if (!(_tmp6_ <= _tmp7_)) {
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
					break;
#line 931 "database.c"
				}
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp8_ = crono_stmt;
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				sqlite3_step (_tmp8_);
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp9_ = i;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp10_ = crono_stmt;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp11_ = sqlite3_column_text (_tmp10_, 0);
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp12_ = g_strdup (_tmp11_);
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_g_free0 (crono_ficha[_tmp9_].id);
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp9_].id = _tmp12_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp13_ = i;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp14_ = crono_stmt;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp15_ = sqlite3_column_text (_tmp14_, 1);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp16_ = g_strdup (_tmp15_);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_g_free0 (crono_ficha[_tmp13_].fecha);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp13_].fecha = _tmp16_;
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp17_ = i;
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp18_ = crono_stmt;
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp19_ = sqlite3_column_text (_tmp18_, 2);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp20_ = g_strdup (_tmp19_);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_g_free0 (crono_ficha[_tmp17_].nombre);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp17_].nombre = _tmp20_;
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp21_ = i;
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp22_ = crono_stmt;
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp23_ = sqlite3_column_text (_tmp22_, 3);
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp24_ = g_strdup (_tmp23_);
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_g_free0 (crono_ficha[_tmp21_].nota);
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp21_].nota = _tmp24_;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp25_ = i;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp26_ = crono_stmt;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp25_].proteger = sqlite3_column_int (_tmp26_, 4);
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp27_ = i;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp28_ = crono_stmt;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp27_].completar = sqlite3_column_int (_tmp28_, 5);
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp29_ = i;
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp30_ = crono_stmt;
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp31_ = sqlite3_column_text (_tmp30_, 6);
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp32_ = g_strdup (_tmp31_);
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_g_free0 (crono_ficha[_tmp29_].color);
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp29_].color = _tmp32_;
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				_tmp33_ = i;
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
				crono_ficha[_tmp33_].visible = TRUE;
#line 1013 "database.c"
			}
		}
	}
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 1019 "database.c"
}


gchar*
crono_formatT (gint valor)
{
	gchar* result = NULL;
	gchar* s_valor = NULL;
	gchar* _tmp0_;
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_strdup ("00");
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	s_valor = _tmp0_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (valor < 10) {
#line 1035 "database.c"
		gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp1_ = g_strdup_printf ("%i", valor);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp2_ = _tmp1_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp3_ = g_strconcat ("0", _tmp2_, NULL);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (s_valor);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		s_valor = _tmp3_;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (_tmp2_);
#line 1051 "database.c"
	} else {
		gchar* _tmp4_;
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp4_ = g_strdup_printf ("%i", valor);
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (s_valor);
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		s_valor = _tmp4_;
#line 1060 "database.c"
	}
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	result = s_valor;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	return result;
#line 1066 "database.c"
}


gint
crono_max_id (void)
{
	gint result = 0;
	sqlite3_stmt* stmt = NULL;
	gchar* query = NULL;
	gchar* _tmp0_;
	sqlite3* _tmp1_;
	sqlite3_stmt* _tmp2_ = NULL;
	gint _tmp3_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_strdup ("SELECT MAX(id) from nota;");
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp0_;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = crono_db;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = sqlite3_prepare_v2 (_tmp1_, query, -1, &_tmp2_, NULL);
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt);
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	stmt = _tmp2_;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp3_;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (stmt);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	result = sqlite3_column_int (stmt, 0);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	return result;
#line 1104 "database.c"
}


gint
crono_crear_ficha (void)
{
	gint result = 0;
	gchar* errmsg = NULL;
	gint _tmp0_;
	gint new_nota = 0;
	gchar* query = NULL;
	gint _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gint _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	sqlite3* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_ = NULL;
	gint _tmp18_;
	gint _tmp19_;
	gint _tmp20_;
	gchar* _tmp21_;
	gint _tmp22_;
	gchar* _tmp23_;
	gint _tmp24_;
	gint _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar* _tmp28_;
	gint _tmp29_;
	gchar* _tmp30_;
	gint _tmp31_;
	gint _tmp32_;
	gint _tmp33_;
	gchar* _tmp34_;
	gint _tmp35_;
	gint _tmp37_;
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = crono_max_nota;
#line 113 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_max_nota = _tmp0_ + 1;
#line 114 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	new_nota = crono_max_id () + 1;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = new_nota;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = g_strdup_printf ("%i", _tmp1_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = _tmp2_;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = g_strconcat ("INSERT INTO nota (id,fecha,nombre,nota,proteger,completar,color) value" \
"s(", _tmp3_, NULL);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = _tmp4_;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = g_strconcat (_tmp5_, ",'00/00/0000','Nota", NULL);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = _tmp6_;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = new_nota;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = g_strdup_printf ("%i", _tmp8_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = _tmp9_;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = g_strconcat (_tmp7_, _tmp10_, NULL);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = _tmp11_;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp13_ = g_strconcat (_tmp12_, "','',0,0,'amarillo');", NULL);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp14_ = _tmp13_;
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp12_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp10_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp7_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp5_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp3_);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp14_;
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp15_ = crono_db;
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp16_ = query;
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp18_ = _sqlite3_exec (_tmp15_, _tmp16_, NULL, NULL, &_tmp17_);
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	errmsg = _tmp17_;
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp18_;
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp19_ = crono_max_nota;
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = new_nota;
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp21_ = g_strdup_printf ("%i", _tmp20_);
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_ficha[_tmp19_].id);
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp19_].id = _tmp21_;
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp22_ = crono_max_nota;
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp23_ = g_strdup ("00/00/0000");
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_ficha[_tmp22_].fecha);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp22_].fecha = _tmp23_;
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp24_ = crono_max_nota;
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp25_ = new_nota;
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp26_ = g_strdup_printf ("%i", _tmp25_);
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp27_ = _tmp26_;
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp28_ = g_strconcat ("Nota", _tmp27_, NULL);
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_ficha[_tmp24_].nombre);
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp24_].nombre = _tmp28_;
#line 120 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp27_);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp29_ = crono_max_nota;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp30_ = g_strdup ("");
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_ficha[_tmp29_].nota);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp29_].nota = _tmp30_;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp31_ = crono_max_nota;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp31_].proteger = 0;
#line 123 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp32_ = crono_max_nota;
#line 123 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp32_].completar = 0;
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp33_ = crono_max_nota;
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp34_ = g_strdup ("amarillo");
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (crono_ficha[_tmp33_].color);
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_ficha[_tmp33_].color = _tmp34_;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp35_ = crono_rc;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (_tmp35_ != SQLITE_OK) {
#line 1272 "database.c"
		const gchar* _tmp36_;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp36_ = errmsg;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		g_print ("Error: %s\n", _tmp36_);
#line 1278 "database.c"
	}
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp37_ = crono_max_nota;
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	result = _tmp37_;
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	return result;
#line 1290 "database.c"
}


void
crono_guardar (const gchar* nombre,
               const gchar* nota,
               const gchar* color,
               const gchar* id)
{
	gchar* errmsg = NULL;
	gchar* query = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gint rc = 0;
	sqlite3* _tmp16_;
	const gchar* _tmp17_;
	gchar* _tmp18_ = NULL;
	gint _tmp19_;
	gint _tmp20_;
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_return_if_fail (nombre != NULL);
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_return_if_fail (nota != NULL);
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_return_if_fail (color != NULL);
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_return_if_fail (id != NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_strconcat ("UPDATE nota SET nombre ='", nombre, NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = _tmp0_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = g_strconcat (_tmp1_, "' ,nota='", NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = _tmp2_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = g_strconcat (_tmp3_, nota, NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = _tmp4_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = g_strconcat (_tmp5_, "', color='", NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = _tmp6_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = g_strconcat (_tmp7_, color, NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = _tmp8_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = g_strconcat (_tmp9_, "'WHERE id=", NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = _tmp10_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = g_strconcat (_tmp11_, id, NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp13_ = _tmp12_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp14_ = g_strconcat (_tmp13_, ";", NULL);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp15_ = _tmp14_;
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp13_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp11_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp9_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp7_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp5_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp3_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp1_);
#line 130 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp15_;
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp16_ = crono_db;
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp17_ = query;
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp19_ = _sqlite3_exec (_tmp16_, _tmp17_, NULL, NULL, &_tmp18_);
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	errmsg = _tmp18_;
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	rc = _tmp19_;
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = rc;
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (_tmp20_ != SQLITE_OK) {
#line 1396 "database.c"
		const gchar* _tmp21_;
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp21_ = errmsg;
#line 133 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		g_print ("Error: %s\n", _tmp21_);
#line 1402 "database.c"
	}
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 1408 "database.c"
}


gint
crono_count_jornadas (void)
{
	gint result = 0;
	sqlite3_stmt* stmt2 = NULL;
	gchar* query2 = NULL;
	gchar* _tmp0_;
	sqlite3* _tmp1_;
	sqlite3_stmt* _tmp2_ = NULL;
	gint _tmp3_;
	const gchar* _tmp4_;
#line 137 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_strdup ("SELECT count(*) from jornada;");
#line 137 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query2 = _tmp0_;
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = crono_db;
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = sqlite3_prepare_v2 (_tmp1_, query2, -1, &_tmp2_, NULL);
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt2);
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	stmt2 = _tmp2_;
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp3_;
#line 139 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (stmt2);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = sqlite3_column_text (stmt2, 0);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	result = atoi (_tmp4_);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query2);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt2);
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	return result;
#line 1449 "database.c"
}


void
crono_guarda_trabajo (gint hx,
                      gint mx,
                      const gchar* lcd)
{
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gchar* mi_fecha = NULL;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GDateTime* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GDateTime* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* errmsg = NULL;
	gchar* query2 = NULL;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	const gchar* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	sqlite3* _tmp39_;
	const gchar* _tmp40_;
	gchar* _tmp41_ = NULL;
	gint _tmp42_;
	gint _tmp43_;
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	g_return_if_fail (lcd != NULL);
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 143 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	now = _tmp0_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = now;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = crono_formatT (g_date_time_get_day_of_month (_tmp1_));
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = _tmp2_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = g_strconcat (_tmp3_, "/", NULL);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = _tmp4_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = now;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = crono_formatT (g_date_time_get_month (_tmp6_));
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = _tmp7_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = _tmp9_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = g_strconcat (_tmp10_, "/", NULL);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = _tmp11_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp13_ = now;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp14_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp13_));
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp15_ = _tmp14_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp16_ = g_strconcat (_tmp12_, _tmp15_, NULL);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp17_ = _tmp16_;
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp15_);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp12_);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp10_);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp8_);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp5_);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp3_);
#line 144 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	mi_fecha = _tmp17_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp18_ = g_strdup_printf ("%i", hx);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp19_ = _tmp18_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = g_strconcat ("UPDATE jornada SET hx=", _tmp19_, NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp21_ = _tmp20_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp22_ = g_strconcat (_tmp21_, ",mx= ", NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp23_ = _tmp22_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp24_ = g_strdup_printf ("%i", mx);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp25_ = _tmp24_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp26_ = g_strconcat (_tmp23_, _tmp25_, NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp27_ = _tmp26_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp28_ = g_strconcat (_tmp27_, ",horas='", NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp29_ = _tmp28_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp30_ = g_strconcat (_tmp29_, lcd, NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp31_ = _tmp30_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp32_ = g_strconcat (_tmp31_, "' WHERE fecha='", NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp33_ = _tmp32_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp34_ = mi_fecha;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp35_ = g_strconcat (_tmp33_, _tmp34_, NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp36_ = _tmp35_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp37_ = g_strconcat (_tmp36_, "';", NULL);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp38_ = _tmp37_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp36_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp33_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp31_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp29_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp27_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp25_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp23_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp21_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp19_);
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query2 = _tmp38_;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp39_ = crono_db;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp40_ = query2;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp42_ = _sqlite3_exec (_tmp39_, _tmp40_, NULL, NULL, &_tmp41_);
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	errmsg = _tmp41_;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp42_;
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp43_ = crono_rc;
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (_tmp43_ != SQLITE_OK) {
#line 1638 "database.c"
		const gchar* _tmp44_;
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_tmp44_ = errmsg;
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		g_print ("Error: %s\n", _tmp44_);
#line 1644 "database.c"
	}
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query2);
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (errmsg);
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (mi_fecha);
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_date_time_unref0 (now);
#line 1654 "database.c"
}


gboolean
crono_if_tareas_hoy (gint id)
{
	gboolean result = FALSE;
	sqlite3_stmt* stmt_tareas = NULL;
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gchar* mi_fecha = NULL;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GDateTime* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GDateTime* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* query = NULL;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar* _tmp28_;
	sqlite3* _tmp29_;
	const gchar* _tmp30_;
	sqlite3_stmt* _tmp31_ = NULL;
	gint _tmp32_;
	sqlite3_stmt* _tmp33_;
	sqlite3_stmt* _tmp34_;
	const gchar* _tmp35_;
#line 153 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 153 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	now = _tmp0_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = now;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = crono_formatT (g_date_time_get_day_of_month (_tmp1_));
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = _tmp2_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = g_strconcat (_tmp3_, "/", NULL);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = _tmp4_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = now;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = crono_formatT (g_date_time_get_month (_tmp6_));
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = _tmp7_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = _tmp9_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = g_strconcat (_tmp10_, "/", NULL);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = _tmp11_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp13_ = now;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp14_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp13_));
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp15_ = _tmp14_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp16_ = g_strconcat (_tmp12_, _tmp15_, NULL);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp17_ = _tmp16_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp15_);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp12_);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp10_);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp8_);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp5_);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp3_);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	mi_fecha = _tmp17_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp18_ = mi_fecha;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp19_ = g_strconcat ("SELECT COUNT(*)  from nota where fecha='", _tmp18_, NULL);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = _tmp19_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp21_ = g_strconcat (_tmp20_, "' and id=", NULL);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp22_ = _tmp21_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp23_ = g_strdup_printf ("%i", id);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp24_ = _tmp23_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp25_ = g_strconcat (_tmp22_, _tmp24_, NULL);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp26_ = _tmp25_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp27_ = g_strconcat (_tmp26_, ";", NULL);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp28_ = _tmp27_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp26_);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp24_);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp22_);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp20_);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp28_;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp29_ = crono_db;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp30_ = query;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp32_ = sqlite3_prepare_v2 (_tmp29_, _tmp30_, -1, &_tmp31_, NULL);
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_tareas);
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	stmt_tareas = _tmp31_;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp32_;
#line 157 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp33_ = stmt_tareas;
#line 157 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (_tmp33_);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp34_ = stmt_tareas;
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp35_ = sqlite3_column_text (_tmp34_, 0);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (atoi (_tmp35_) > 0) {
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		result = TRUE;
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (mi_fecha);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_date_time_unref0 (now);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_sqlite3_finalize0 (stmt_tareas);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		return result;
#line 1820 "database.c"
	} else {
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		result = FALSE;
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (mi_fecha);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_date_time_unref0 (now);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_sqlite3_finalize0 (stmt_tareas);
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		return result;
#line 1834 "database.c"
	}
#line 151 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 151 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (mi_fecha);
#line 151 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_date_time_unref0 (now);
#line 151 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_tareas);
#line 1844 "database.c"
}


gboolean
crono_now_tareas (void)
{
	gboolean result = FALSE;
	sqlite3_stmt* stmt_tareas = NULL;
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gchar* mi_fecha = NULL;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GDateTime* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GDateTime* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* query = NULL;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	sqlite3* _tmp23_;
	const gchar* _tmp24_;
	sqlite3_stmt* _tmp25_ = NULL;
	gint _tmp26_;
	sqlite3_stmt* _tmp27_;
	sqlite3_stmt* _tmp28_;
	const gchar* _tmp29_;
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	now = _tmp0_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp1_ = now;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp2_ = crono_formatT (g_date_time_get_day_of_month (_tmp1_));
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp3_ = _tmp2_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp4_ = g_strconcat (_tmp3_, "/", NULL);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp5_ = _tmp4_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp6_ = now;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp7_ = crono_formatT (g_date_time_get_month (_tmp6_));
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp8_ = _tmp7_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp10_ = _tmp9_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp11_ = g_strconcat (_tmp10_, "/", NULL);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp12_ = _tmp11_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp13_ = now;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp14_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp13_));
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp15_ = _tmp14_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp16_ = g_strconcat (_tmp12_, _tmp15_, NULL);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp17_ = _tmp16_;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp15_);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp12_);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp10_);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp8_);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp5_);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp3_);
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	mi_fecha = _tmp17_;
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp18_ = mi_fecha;
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp19_ = g_strconcat ("SELECT COUNT(*)  from nota where fecha='", _tmp18_, NULL);
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp20_ = _tmp19_;
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp21_ = g_strconcat (_tmp20_, "';", NULL);
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp22_ = _tmp21_;
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (_tmp20_);
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	query = _tmp22_;
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp23_ = crono_db;
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp24_ = query;
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp26_ = sqlite3_prepare_v2 (_tmp23_, _tmp24_, -1, &_tmp25_, NULL);
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_tareas);
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	stmt_tareas = _tmp25_;
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	crono_rc = _tmp26_;
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp27_ = stmt_tareas;
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	sqlite3_step (_tmp27_);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp28_ = stmt_tareas;
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_tmp29_ = sqlite3_column_text (_tmp28_, 0);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	if (atoi (_tmp29_) > 0) {
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		result = TRUE;
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (mi_fecha);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_date_time_unref0 (now);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_sqlite3_finalize0 (stmt_tareas);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		return result;
#line 1986 "database.c"
	} else {
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		result = FALSE;
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (query);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_free0 (mi_fecha);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_g_date_time_unref0 (now);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		_sqlite3_finalize0 (stmt_tareas);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
		return result;
#line 2000 "database.c"
	}
#line 160 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (query);
#line 160 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_free0 (mi_fecha);
#line 160 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_g_date_time_unref0 (now);
#line 160 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/database.vala"
	_sqlite3_finalize0 (stmt_tareas);
#line 2010 "database.c"
}



