/* jornada.c generated by valac 0.40.8, the Vala compiler
 * generated from jornada.vala, do not modify */

/*
Cronotas (c) Didapax Sistem Daniel Alfonsi 
2019
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <sqlite3.h>
#include <stdlib.h>
#include <string.h>


#define CRONO_TYPE_DIALOG_JORNADA (crono_dialog_jornada_get_type ())
#define CRONO_DIALOG_JORNADA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornada))
#define CRONO_DIALOG_JORNADA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornadaClass))
#define CRONO_IS_DIALOG_JORNADA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_DIALOG_JORNADA))
#define CRONO_IS_DIALOG_JORNADA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_DIALOG_JORNADA))
#define CRONO_DIALOG_JORNADA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornadaClass))

typedef struct _cronodialog_jornada cronodialog_jornada;
typedef struct _cronodialog_jornadaClass cronodialog_jornadaClass;
typedef struct _cronodialog_jornadaPrivate cronodialog_jornadaPrivate;
enum  {
	CRONO_DIALOG_JORNADA_0_PROPERTY,
	CRONO_DIALOG_JORNADA_NUM_PROPERTIES
};
static GParamSpec* crono_dialog_jornada_properties[CRONO_DIALOG_JORNADA_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))

#define CRONO_TYPE_F_CONFIG (crono_f_config_get_type ())
typedef struct _cronof_config cronof_config;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _cronodialog_jornada {
	GtkDialog parent_instance;
	cronodialog_jornadaPrivate * priv;
};

struct _cronodialog_jornadaClass {
	GtkDialogClass parent_class;
};

struct _cronodialog_jornadaPrivate {
	GtkBuilder* builder;
	GtkDialog* dialog;
	GtkTreeView* lista;
	GtkComboBox* combo_mes;
	GtkLabel* label_total;
	GtkLabel* lfecha;
	GtkLabel* ldia;
	GtkLabel* lmes;
	GtkCalendar* calendar;
	GtkListStore* list_box;
	GtkTreeIter iter_box;
	GtkCellRendererText* cell;
	sqlite3_stmt* stmt_jornada;
	GtkListStore* list_store;
	GtkTreeIter iter;
};

struct _cronof_config {
	gchar* id;
	gchar* ruta;
	gchar* color;
};


static gpointer crono_dialog_jornada_parent_class = NULL;
extern cronof_config crono_fconfig;
extern sqlite3* crono_db;
extern gint crono_rc;

GType crono_dialog_jornada_get_type (void) G_GNUC_CONST;
#define CRONO_DIALOG_JORNADA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornadaPrivate))
cronodialog_jornada* crono_dialog_jornada_new (void);
cronodialog_jornada* crono_dialog_jornada_construct (GType object_type);
GType crono_f_config_get_type (void) G_GNUC_CONST;
cronof_config* crono_f_config_dup (const cronof_config* self);
void crono_f_config_free (cronof_config* self);
void crono_f_config_copy (const cronof_config* self,
                          cronof_config* dest);
void crono_f_config_destroy (cronof_config* self);
void crono_dialog_jornada_cursor_changed (cronodialog_jornada* self);
static void _crono_dialog_jornada_cursor_changed_gtk_tree_view_cursor_changed (GtkTreeView* _sender,
                                                                        gpointer self);
void crono_dialog_jornada_changed (cronodialog_jornada* self);
static void _crono_dialog_jornada_changed_gtk_combo_box_changed (GtkComboBox* _sender,
                                                          gpointer self);
void crono_dialog_jornada_llenar_meses (cronodialog_jornada* self);
gchar* crono_dialog_jornada_sum_total (cronodialog_jornada* self,
                                       const gchar* mes);
gchar* crono_formatT (gint valor);
static void crono_dialog_jornada_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	return self ? g_object_ref (self) : NULL;
#line 115 "jornada.c"
}


static void
_crono_dialog_jornada_cursor_changed_gtk_tree_view_cursor_changed (GtkTreeView* _sender,
                                                                   gpointer self)
{
#line 35 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	crono_dialog_jornada_cursor_changed ((cronodialog_jornada*) self);
#line 125 "jornada.c"
}


static void
_crono_dialog_jornada_changed_gtk_combo_box_changed (GtkComboBox* _sender,
                                                     gpointer self)
{
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	crono_dialog_jornada_changed ((cronodialog_jornada*) self);
#line 135 "jornada.c"
}


cronodialog_jornada*
crono_dialog_jornada_construct (GType object_type)
{
	cronodialog_jornada * self = NULL;
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	GtkBuilder* _tmp1_;
	GtkBuilder* _tmp2_;
	cronof_config _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GtkBuilder* _tmp7_;
	GtkBuilder* _tmp8_;
	GObject* _tmp9_;
	GtkDialog* _tmp10_;
	GtkBuilder* _tmp11_;
	GObject* _tmp12_;
	GtkTreeView* _tmp13_;
	GtkTreeView* _tmp14_;
	GtkBuilder* _tmp15_;
	GObject* _tmp16_;
	GtkCalendar* _tmp17_;
	GtkBuilder* _tmp18_;
	GObject* _tmp19_;
	GtkComboBox* _tmp20_;
	GtkComboBox* _tmp21_;
	GtkBuilder* _tmp22_;
	GObject* _tmp23_;
	GtkLabel* _tmp24_;
	GtkBuilder* _tmp25_;
	GObject* _tmp26_;
	GtkLabel* _tmp27_;
	GtkBuilder* _tmp28_;
	GObject* _tmp29_;
	GtkLabel* _tmp30_;
	GtkBuilder* _tmp31_;
	GObject* _tmp32_;
	GtkLabel* _tmp33_;
	GtkTreeView* _tmp34_;
	GtkCellRendererText* _tmp35_;
	GtkTreeView* _tmp36_;
	GtkCellRendererText* _tmp37_;
	GtkDialog* _tmp38_;
	GtkLabel* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	GtkLabel* _tmp42_;
	GtkCalendar* _tmp43_;
	GtkCalendar* _tmp44_;
	GtkCalendar* _tmp45_;
	GError * _inner_error_ = NULL;
#line 28 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self = (cronodialog_jornada*) g_object_new (object_type, NULL);
#line 29 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 29 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	now = _tmp0_;
#line 30 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp1_ = gtk_builder_new ();
#line 30 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (_tmp1_) {
#line 30 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_object_set_data ((GObject *) _tmp1_, "vala-creation-function", "crono.dialog_jornada.new");
#line 203 "jornada.c"
	}
#line 30 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->builder);
#line 30 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->builder = _tmp1_;
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp2_ = self->priv->builder;
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp3_ = crono_fconfig;
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp4_ = _tmp3_.ruta;
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp5_ = g_strconcat (_tmp4_, "jornada.ui", NULL);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp6_ = _tmp5_;
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_builder_add_from_file (_tmp2_, _tmp6_, &_inner_error_);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (_tmp6_);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_date_time_unref0 (now);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_clear_error (&_inner_error_);
#line 31 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		return NULL;
#line 233 "jornada.c"
	}
#line 32 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp7_ = self->priv->builder;
#line 32 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_builder_connect_signals (_tmp7_, NULL);
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp8_ = self->priv->builder;
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp9_ = gtk_builder_get_object (_tmp8_, "jornadas");
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp10_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp9_, gtk_dialog_get_type ()) ? ((GtkDialog*) _tmp9_) : NULL);
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->dialog);
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->dialog = _tmp10_;
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp11_ = self->priv->builder;
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp12_ = gtk_builder_get_object (_tmp11_, "lista");
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp13_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp12_, gtk_tree_view_get_type ()) ? ((GtkTreeView*) _tmp12_) : NULL);
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->lista);
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->lista = _tmp13_;
#line 35 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_ = self->priv->lista;
#line 35 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_signal_connect_object (_tmp14_, "cursor-changed", (GCallback) _crono_dialog_jornada_cursor_changed_gtk_tree_view_cursor_changed, self, 0);
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp15_ = self->priv->builder;
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp16_ = gtk_builder_get_object (_tmp15_, "calendar");
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp17_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp16_, gtk_calendar_get_type ()) ? ((GtkCalendar*) _tmp16_) : NULL);
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->calendar);
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->calendar = _tmp17_;
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp18_ = self->priv->builder;
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp19_ = gtk_builder_get_object (_tmp18_, "combo_mes");
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp20_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp19_, gtk_combo_box_get_type ()) ? ((GtkComboBox*) _tmp19_) : NULL);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->combo_mes);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->combo_mes = _tmp20_;
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp21_ = self->priv->combo_mes;
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_signal_connect_object (_tmp21_, "changed", (GCallback) _crono_dialog_jornada_changed_gtk_combo_box_changed, self, 0);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp22_ = self->priv->builder;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp23_ = gtk_builder_get_object (_tmp22_, "label_total");
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp24_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp23_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp23_) : NULL);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->label_total);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->label_total = _tmp24_;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp25_ = self->priv->builder;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp26_ = gtk_builder_get_object (_tmp25_, "lfecha");
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp27_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp26_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp26_) : NULL);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->lfecha);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->lfecha = _tmp27_;
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp28_ = self->priv->builder;
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp29_ = gtk_builder_get_object (_tmp28_, "ldia");
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp30_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp29_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp29_) : NULL);
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->ldia);
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->ldia = _tmp30_;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp31_ = self->priv->builder;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp32_ = gtk_builder_get_object (_tmp31_, "lmes");
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp33_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp32_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp32_) : NULL);
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->lmes);
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->lmes = _tmp33_;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp34_ = self->priv->lista;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp35_ = self->priv->cell;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_tree_view_insert_column_with_attributes (_tmp34_, -1, "Fecha", G_TYPE_CHECK_INSTANCE_CAST (_tmp35_, gtk_cell_renderer_get_type (), GtkCellRenderer), "text", 0, NULL);
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp36_ = self->priv->lista;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp37_ = self->priv->cell;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_tree_view_insert_column_with_attributes (_tmp36_, -1, "Horas Trabajadas", G_TYPE_CHECK_INSTANCE_CAST (_tmp37_, gtk_cell_renderer_get_type (), GtkCellRenderer), "text", 1, NULL);
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp38_ = self->priv->dialog;
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_widget_show_all (G_TYPE_CHECK_INSTANCE_CAST (_tmp38_, gtk_widget_get_type (), GtkWidget));
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	crono_dialog_jornada_llenar_meses (self);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp39_ = self->priv->label_total;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp40_ = crono_dialog_jornada_sum_total (self, "Todo");
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp41_ = _tmp40_;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_label_set_label (_tmp39_, _tmp41_);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (_tmp41_);
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp42_ = self->priv->lmes;
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_label_set_label (_tmp42_, "Todos");
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp43_ = self->priv->calendar;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_set (_tmp43_, "year", g_date_time_get_year (now), NULL);
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp44_ = self->priv->calendar;
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_set (_tmp44_, "month", g_date_time_get_month (now) - 1, NULL);
#line 51 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp45_ = self->priv->calendar;
#line 51 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_set (_tmp45_, "day", g_date_time_get_day_of_month (now), NULL);
#line 28 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_date_time_unref0 (now);
#line 28 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	return self;
#line 375 "jornada.c"
}


cronodialog_jornada*
crono_dialog_jornada_new (void)
{
#line 28 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	return crono_dialog_jornada_construct (CRONO_TYPE_DIALOG_JORNADA);
#line 384 "jornada.c"
}


static gchar*
string_slice (const gchar* self,
              glong start,
              glong end)
{
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_;
	gint _tmp1_;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp6_ = FALSE;
	gchar* _tmp8_;
#line 1369 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1370 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1370 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1370 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	string_length = (glong) _tmp1_;
#line 1371 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (start < ((glong) 0)) {
#line 410 "jornada.c"
		glong _tmp2_;
#line 1372 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp2_ = string_length;
#line 1372 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		start = _tmp2_ + start;
#line 416 "jornada.c"
	}
#line 1374 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (end < ((glong) 0)) {
#line 420 "jornada.c"
		glong _tmp3_;
#line 1375 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp3_ = string_length;
#line 1375 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		end = _tmp3_ + end;
#line 426 "jornada.c"
	}
#line 1377 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (start >= ((glong) 0)) {
#line 430 "jornada.c"
		glong _tmp5_;
#line 1377 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp5_ = string_length;
#line 1377 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp4_ = start <= _tmp5_;
#line 436 "jornada.c"
	} else {
#line 1377 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp4_ = FALSE;
#line 440 "jornada.c"
	}
#line 1377 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp4_, NULL);
#line 1378 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (end >= ((glong) 0)) {
#line 446 "jornada.c"
		glong _tmp7_;
#line 1378 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp7_ = string_length;
#line 1378 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp6_ = end <= _tmp7_;
#line 452 "jornada.c"
	} else {
#line 1378 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp6_ = FALSE;
#line 456 "jornada.c"
	}
#line 1378 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp6_, NULL);
#line 1379 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (start <= end, NULL);
#line 1380 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp8_ = g_strndup (((gchar*) self) + start, (gsize) (end - start));
#line 1380 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = _tmp8_;
#line 1380 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 468 "jornada.c"
}


void
crono_dialog_jornada_cursor_changed (cronodialog_jornada* self)
{
	gchar* dia1 = NULL;
	gchar* dia2 = NULL;
	GtkTreeSelection* sel = NULL;
	GtkTreeModel* model = NULL;
	GtkTreeIter iter1 = {0};
	GValue val1 = {0};
	GValue val2 = {0};
	GtkTreeView* _tmp0_;
	GtkTreeSelection* _tmp1_;
	GtkTreeSelection* _tmp2_;
	gboolean ff = FALSE;
	GtkTreeSelection* _tmp3_;
	GtkTreeModel* _tmp4_ = NULL;
	GtkTreeIter _tmp5_ = {0};
	gboolean _tmp6_;
	GtkTreeModel* _tmp7_;
	GtkListStore* _tmp8_;
	GtkTreeIter _tmp9_;
	GValue _tmp10_ = {0};
	GtkListStore* _tmp11_;
	GtkTreeIter _tmp12_;
	GValue _tmp13_ = {0};
	GValue _tmp14_;
	gchar* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	const gchar* _tmp18_;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_return_if_fail (CRONO_IS_DIALOG_JORNADA (self));
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp0_ = self->priv->lista;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp1_ = gtk_tree_view_get_selection (_tmp0_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (sel);
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	sel = _tmp2_;
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp3_ = sel;
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp6_ = gtk_tree_selection_get_selected (_tmp3_, &_tmp4_, &_tmp5_);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (model);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp7_ = _g_object_ref0 (_tmp4_);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	model = _tmp7_;
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	iter1 = _tmp5_;
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	ff = _tmp6_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp8_ = self->priv->list_store;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp9_ = iter1;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_tree_model_get_value (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, gtk_tree_model_get_type (), GtkTreeModel), &_tmp9_, 0, &_tmp10_);
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_IS_VALUE (&val1) ? (g_value_unset (&val1), NULL) : NULL;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	val1 = _tmp10_;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp11_ = self->priv->list_store;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp12_ = iter1;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_tree_model_get_value (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, gtk_tree_model_get_type (), GtkTreeModel), &_tmp12_, 1, &_tmp13_);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_IS_VALUE (&val2) ? (g_value_unset (&val2), NULL) : NULL;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	val2 = _tmp13_;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_ = val1;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp15_ = g_strdup (g_value_get_string (&_tmp14_));
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (dia1);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	dia1 = _tmp15_;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp16_ = dia1;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp17_ = string_slice (_tmp16_, (glong) 0, (glong) 2);
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (dia2);
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	dia2 = _tmp17_;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp18_ = dia2;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (_tmp18_ != NULL) {
#line 568 "jornada.c"
		GtkLabel* _tmp19_;
		const gchar* _tmp20_;
		GtkLabel* _tmp21_;
		GValue _tmp22_;
		GtkCalendar* _tmp23_;
		const gchar* _tmp24_;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp19_ = self->priv->lfecha;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp20_ = dia1;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		gtk_label_set_label (_tmp19_, _tmp20_);
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp21_ = self->priv->ldia;
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp22_ = val2;
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		gtk_label_set_label (_tmp21_, g_value_get_string (&_tmp22_));
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp23_ = self->priv->calendar;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp24_ = dia2;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_object_set (_tmp23_, "day", atoi (_tmp24_), NULL);
#line 593 "jornada.c"
	}
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_IS_VALUE (&val2) ? (g_value_unset (&val2), NULL) : NULL;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_IS_VALUE (&val1) ? (g_value_unset (&val1), NULL) : NULL;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (model);
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (sel);
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (dia2);
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (dia1);
#line 607 "jornada.c"
}


gchar*
crono_dialog_jornada_sum_total (cronodialog_jornada* self,
                                const gchar* mes)
{
	gchar* result = NULL;
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gchar* query = NULL;
	sqlite3* _tmp12_;
	const gchar* _tmp13_;
	sqlite3_stmt* _tmp14_ = NULL;
	gint _tmp15_;
	GtkListStore* _tmp16_;
	GtkTreeView* _tmp26_;
	GtkListStore* _tmp27_;
	sqlite3* _tmp39_;
	const gchar* _tmp40_;
	sqlite3_stmt* _tmp41_ = NULL;
	gint _tmp42_;
	sqlite3_stmt* _tmp43_;
	sqlite3_stmt* _tmp44_;
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_return_val_if_fail (CRONO_IS_DIALOG_JORNADA (self), NULL);
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_return_val_if_fail (mes != NULL, NULL);
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	now = _tmp0_;
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (g_strcmp0 (mes, "Todo") == 0) {
#line 642 "jornada.c"
		gchar* _tmp1_;
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp1_ = g_strdup ("SELECT *  FROM jornada;");
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (query);
#line 76 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		query = _tmp1_;
#line 650 "jornada.c"
	} else {
		gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		GDateTime* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp2_ = g_strconcat ("SELECT *  FROM jornada where mes='", mes, NULL);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp3_ = _tmp2_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp4_ = g_strconcat (_tmp3_, "' and ano='", NULL);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp5_ = _tmp4_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp6_ = now;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp7_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp6_));
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp8_ = _tmp7_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp10_ = _tmp9_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp11_ = g_strconcat (_tmp10_, "';", NULL);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (query);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		query = _tmp11_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp10_);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp8_);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp5_);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp3_);
#line 694 "jornada.c"
	}
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp12_ = crono_db;
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp13_ = query;
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp15_ = sqlite3_prepare_v2 (_tmp12_, _tmp13_, -1, &_tmp14_, NULL);
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_sqlite3_finalize0 (self->priv->stmt_jornada);
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->stmt_jornada = _tmp14_;
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	crono_rc = _tmp15_;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp16_ = self->priv->list_store;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_list_store_clear (_tmp16_);
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	while (TRUE) {
#line 714 "jornada.c"
		sqlite3_stmt* _tmp17_;
		GtkListStore* _tmp18_;
		GtkTreeIter _tmp19_ = {0};
		GtkListStore* _tmp20_;
		GtkTreeIter _tmp21_;
		sqlite3_stmt* _tmp22_;
		const gchar* _tmp23_;
		sqlite3_stmt* _tmp24_;
		const gchar* _tmp25_;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp17_ = self->priv->stmt_jornada;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		if (!(sqlite3_step (_tmp17_) == SQLITE_ROW)) {
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
			break;
#line 730 "jornada.c"
		}
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp18_ = self->priv->list_store;
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		gtk_list_store_append (_tmp18_, &_tmp19_);
#line 81 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		self->priv->iter = _tmp19_;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp20_ = self->priv->list_store;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp21_ = self->priv->iter;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp22_ = self->priv->stmt_jornada;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp23_ = sqlite3_column_text (_tmp22_, 1);
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp24_ = self->priv->stmt_jornada;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp25_ = sqlite3_column_text (_tmp24_, 4);
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		gtk_list_store_set (_tmp20_, &_tmp21_, 0, _tmp23_, 1, _tmp25_, -1);
#line 752 "jornada.c"
	}
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp26_ = self->priv->lista;
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp27_ = self->priv->list_store;
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_tree_view_set_model (_tmp26_, G_TYPE_CHECK_INSTANCE_CAST (_tmp27_, gtk_tree_model_get_type (), GtkTreeModel));
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (g_strcmp0 (mes, "Todo") == 0) {
#line 762 "jornada.c"
		gchar* _tmp28_;
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp28_ = g_strdup ("select sum(hx) from jornada;");
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (query);
#line 85 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		query = _tmp28_;
#line 770 "jornada.c"
	} else {
		gchar* _tmp29_;
		gchar* _tmp30_;
		gchar* _tmp31_;
		gchar* _tmp32_;
		GDateTime* _tmp33_;
		gchar* _tmp34_;
		gchar* _tmp35_;
		gchar* _tmp36_;
		gchar* _tmp37_;
		gchar* _tmp38_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp29_ = g_strconcat ("select sum(hx) from jornada where mes='", mes, NULL);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp30_ = _tmp29_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp31_ = g_strconcat (_tmp30_, "' and ano='", NULL);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp32_ = _tmp31_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp33_ = now;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp34_ = g_strdup_printf ("%i", g_date_time_get_year (_tmp33_));
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp35_ = _tmp34_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp36_ = g_strconcat (_tmp32_, _tmp35_, NULL);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp37_ = _tmp36_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp38_ = g_strconcat (_tmp37_, "';", NULL);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (query);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		query = _tmp38_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp37_);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp35_);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp32_);
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp30_);
#line 814 "jornada.c"
	}
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp39_ = crono_db;
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp40_ = query;
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp42_ = sqlite3_prepare_v2 (_tmp39_, _tmp40_, -1, &_tmp41_, NULL);
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_sqlite3_finalize0 (self->priv->stmt_jornada);
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->stmt_jornada = _tmp41_;
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	crono_rc = _tmp42_;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp43_ = self->priv->stmt_jornada;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	sqlite3_step (_tmp43_);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp44_ = self->priv->stmt_jornada;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (sqlite3_column_type (_tmp44_, 0) != SQLITE_NULL) {
#line 836 "jornada.c"
		sqlite3_stmt* _tmp45_;
		const gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
		gchar* _tmp49_;
		gchar* _tmp50_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp45_ = self->priv->stmt_jornada;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp46_ = sqlite3_column_text (_tmp45_, 0);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp47_ = g_strdup_printf ("%i", atoi (_tmp46_) / 3600);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp48_ = _tmp47_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp49_ = g_strconcat (_tmp48_, " Horas Trabajadas", NULL);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp50_ = _tmp49_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (_tmp48_);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		result = _tmp50_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (query);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_date_time_unref0 (now);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		return result;
#line 865 "jornada.c"
	} else {
		gchar* _tmp51_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_tmp51_ = g_strdup ("0 Horas Trabajadas");
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		result = _tmp51_;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_free0 (query);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		_g_date_time_unref0 (now);
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		return result;
#line 878 "jornada.c"
	}
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (query);
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_date_time_unref0 (now);
#line 884 "jornada.c"
}


void
crono_dialog_jornada_changed (cronodialog_jornada* self)
{
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gchar** mes = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar** _tmp14_;
	gint mes_length1;
	gint _mes_size_;
	GValue val1 = {0};
	gboolean ff = FALSE;
	GtkComboBox* _tmp15_;
	GtkTreeIter _tmp16_ = {0};
	gboolean _tmp17_;
	GtkListStore* _tmp18_;
	GtkTreeIter _tmp19_;
	GValue _tmp20_ = {0};
	GtkLabel* _tmp21_;
	GValue _tmp22_;
	const gchar* _tmp23_;
	GtkLabel* _tmp24_;
	GValue _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	GtkCalendar* _tmp28_;
	GtkCalendar* _tmp29_;
	GValue _tmp30_;
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_return_if_fail (CRONO_IS_DIALOG_JORNADA (self));
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	now = _tmp0_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp1_ = g_strdup ("Todo");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp2_ = g_strdup ("Enero");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp3_ = g_strdup ("Febrero");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp4_ = g_strdup ("Marzo");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp5_ = g_strdup ("Abril");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp6_ = g_strdup ("Mayo");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp7_ = g_strdup ("Junio");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp8_ = g_strdup ("Julio");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp9_ = g_strdup ("Agosto");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp10_ = g_strdup ("Septiembre");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp11_ = g_strdup ("Octubre");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp12_ = g_strdup ("Noviembre");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp13_ = g_strdup ("Diciembre");
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_ = g_new0 (gchar*, 13 + 1);
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[0] = _tmp1_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[1] = _tmp2_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[2] = _tmp3_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[3] = _tmp4_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[4] = _tmp5_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[5] = _tmp6_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[6] = _tmp7_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[7] = _tmp8_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[8] = _tmp9_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[9] = _tmp10_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[10] = _tmp11_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[11] = _tmp12_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp14_[12] = _tmp13_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	mes = _tmp14_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	mes_length1 = 13;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_mes_size_ = mes_length1;
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp15_ = self->priv->combo_mes;
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp17_ = gtk_combo_box_get_active_iter (_tmp15_, &_tmp16_);
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->iter_box = _tmp16_;
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	ff = _tmp17_;
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp18_ = self->priv->list_box;
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp19_ = self->priv->iter_box;
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_tree_model_get_value (G_TYPE_CHECK_INSTANCE_CAST (_tmp18_, gtk_tree_model_get_type (), GtkTreeModel), &_tmp19_, 0, &_tmp20_);
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_IS_VALUE (&val1) ? (g_value_unset (&val1), NULL) : NULL;
#line 96 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	val1 = _tmp20_;
#line 97 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp21_ = self->priv->lmes;
#line 97 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp22_ = val1;
#line 97 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp23_ = mes[atoi (g_value_get_string (&_tmp22_))];
#line 97 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_label_set_label (_tmp21_, _tmp23_);
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp24_ = self->priv->label_total;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp25_ = val1;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp26_ = crono_dialog_jornada_sum_total (self, g_value_get_string (&_tmp25_));
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp27_ = _tmp26_;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_label_set_label (_tmp24_, _tmp27_);
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_free0 (_tmp27_);
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp28_ = self->priv->calendar;
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_set (_tmp28_, "year", g_date_time_get_year (now), NULL);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp29_ = self->priv->calendar;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp30_ = val1;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_set (_tmp29_, "month", atoi (g_value_get_string (&_tmp30_)) - 1, NULL);
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_IS_VALUE (&val1) ? (g_value_unset (&val1), NULL) : NULL;
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	mes = (_vala_array_free (mes, mes_length1, (GDestroyNotify) g_free), NULL);
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_date_time_unref0 (now);
#line 1048 "jornada.c"
}


void
crono_dialog_jornada_llenar_meses (cronodialog_jornada* self)
{
	GtkCellRendererText* cell_box = NULL;
	GtkCellRendererText* _tmp0_;
	GtkListStore* _tmp1_;
	GtkComboBox* _tmp12_;
	GtkListStore* _tmp13_;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_return_if_fail (CRONO_IS_DIALOG_JORNADA (self));
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp0_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (_tmp0_) {
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.dialog_jornada.llenar_meses");
#line 1068 "jornada.c"
	}
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_ref_sink (_tmp0_);
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	cell_box = _tmp0_;
#line 104 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp1_ = self->priv->list_box;
#line 104 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_list_store_clear (_tmp1_);
#line 1078 "jornada.c"
	{
		gint i = 0;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		i = 1;
#line 1083 "jornada.c"
		{
			gboolean _tmp2_ = FALSE;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
			_tmp2_ = TRUE;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
			while (TRUE) {
#line 1090 "jornada.c"
				gint _tmp4_;
				GtkListStore* _tmp5_;
				GtkTreeIter _tmp6_ = {0};
				GtkListStore* _tmp7_;
				GtkTreeIter _tmp8_;
				gint _tmp9_;
				gchar* _tmp10_;
				gchar* _tmp11_;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				if (!_tmp2_) {
#line 1101 "jornada.c"
					gint _tmp3_;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
					_tmp3_ = i;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
					i = _tmp3_ + 1;
#line 1107 "jornada.c"
				}
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp2_ = FALSE;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp4_ = i;
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				if (!(_tmp4_ <= 12)) {
#line 105 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
					break;
#line 1117 "jornada.c"
				}
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp5_ = self->priv->list_box;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				gtk_list_store_append (_tmp5_, &_tmp6_);
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				self->priv->iter_box = _tmp6_;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp7_ = self->priv->list_box;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp8_ = self->priv->iter_box;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp9_ = i;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp10_ = crono_formatT (_tmp9_);
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_tmp11_ = _tmp10_;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				gtk_list_store_set (_tmp7_, &_tmp8_, 0, _tmp11_, -1);
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
				_g_free0 (_tmp11_);
#line 1139 "jornada.c"
			}
		}
	}
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp12_ = self->priv->combo_mes;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp13_ = self->priv->list_box;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	gtk_combo_box_set_model (_tmp12_, G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, gtk_tree_model_get_type (), GtkTreeModel));
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (cell_box);
#line 1151 "jornada.c"
}


static void
crono_dialog_jornada_class_init (cronodialog_jornadaClass * klass)
{
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	crono_dialog_jornada_parent_class = g_type_class_peek_parent (klass);
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_type_class_add_private (klass, sizeof (cronodialog_jornadaPrivate));
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_OBJECT_CLASS (klass)->finalize = crono_dialog_jornada_finalize;
#line 1164 "jornada.c"
}


static void
crono_dialog_jornada_instance_init (cronodialog_jornada * self)
{
	GtkListStore* _tmp0_;
	GtkCellRendererText* _tmp1_;
	GtkListStore* _tmp2_;
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv = CRONO_DIALOG_JORNADA_GET_PRIVATE (self);
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp0_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (_tmp0_) {
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "");
#line 1182 "jornada.c"
	}
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->list_box = _tmp0_;
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp1_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (_tmp1_) {
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_object_set_data ((GObject *) _tmp1_, "vala-creation-function", "");
#line 1192 "jornada.c"
	}
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	g_object_ref_sink (_tmp1_);
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->cell = _tmp1_;
#line 25 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_tmp2_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING, -1);
#line 25 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	if (_tmp2_) {
#line 25 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
		g_object_set_data ((GObject *) _tmp2_, "vala-creation-function", "");
#line 1204 "jornada.c"
	}
#line 25 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self->priv->list_store = _tmp2_;
#line 1208 "jornada.c"
}


static void
crono_dialog_jornada_finalize (GObject * obj)
{
	cronodialog_jornada * self;
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CRONO_TYPE_DIALOG_JORNADA, cronodialog_jornada);
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->builder);
#line 13 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->dialog);
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->lista);
#line 15 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->combo_mes);
#line 16 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->label_total);
#line 17 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->lfecha);
#line 18 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->ldia);
#line 19 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->lmes);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->calendar);
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->list_box);
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->cell);
#line 24 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_sqlite3_finalize0 (self->priv->stmt_jornada);
#line 25 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	_g_object_unref0 (self->priv->list_store);
#line 11 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/jornada.vala"
	G_OBJECT_CLASS (crono_dialog_jornada_parent_class)->finalize (obj);
#line 1246 "jornada.c"
}


GType
crono_dialog_jornada_get_type (void)
{
	static volatile gsize crono_dialog_jornada_type_id__volatile = 0;
	if (g_once_init_enter (&crono_dialog_jornada_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (cronodialog_jornadaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) crono_dialog_jornada_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (cronodialog_jornada), 0, (GInstanceInitFunc) crono_dialog_jornada_instance_init, NULL };
		GType crono_dialog_jornada_type_id;
		crono_dialog_jornada_type_id = g_type_register_static (gtk_dialog_get_type (), "cronodialog_jornada", &g_define_type_info, 0);
		g_once_init_leave (&crono_dialog_jornada_type_id__volatile, crono_dialog_jornada_type_id);
	}
	return crono_dialog_jornada_type_id__volatile;
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



