/* tab.c generated by valac 0.40.8, the Vala compiler
 * generated from tab.vala, do not modify */

/*
Cronotas (c) Didapax Sistem Daniel Alfonsi 
2019
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <sqlite3.h>


#define CRONO_TYPE_TAB (crono_tab_get_type ())
#define CRONO_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CRONO_TYPE_TAB, cronotab))
#define CRONO_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CRONO_TYPE_TAB, cronotabClass))
#define CRONO_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CRONO_TYPE_TAB))
#define CRONO_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CRONO_TYPE_TAB))
#define CRONO_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CRONO_TYPE_TAB, cronotabClass))

typedef struct _cronotab cronotab;
typedef struct _cronotabClass cronotabClass;
typedef struct _cronotabPrivate cronotabPrivate;
enum  {
	CRONO_TAB_0_PROPERTY,
	CRONO_TAB_NUM_PROPERTIES
};
static GParamSpec* crono_tab_properties[CRONO_TAB_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CRONO_TYPE_F_CONFIG (crono_f_config_get_type ())
typedef struct _cronof_config cronof_config;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

#define CRONO_TYPE_F_NOTAS (crono_f_notas_get_type ())
typedef struct _cronof_notas cronof_notas;

struct _cronotab {
	GtkWindow parent_instance;
	cronotabPrivate * priv;
	GtkWidget* minimize;
	GtkWidget* ico_cerrar;
	GtkWidget* ico_campana;
	GtkWidget* ico_candado;
};

struct _cronotabClass {
	GtkWindowClass parent_class;
};

struct _cronotabPrivate {
	GtkBuilder* builder;
	GtkWindow* window;
	GtkButton* btn_fecha;
	GtkButton* cerrar;
	GtkButton* nota_fecha;
	GtkTextView* textnota;
	GtkCalendar* calendar;
	GtkDialog* fecha;
	GtkMenuItem* menu_proteger;
	GtkCheckMenuItem* menu_above;
	GtkMenuItem* menu_guardar;
	GtkButton* campana;
	GtkButton* img_proteger;
	guint time_bar;
	gint tmp;
	gboolean state;
};

struct _cronof_config {
	gchar* id;
	gchar* ruta;
	gchar* color;
};

struct _cronof_notas {
	gchar* id;
	gchar* fecha;
	gchar* nombre;
	gchar* nota;
	gint proteger;
	gint completar;
	gchar* color;
	gboolean visible;
};


static gpointer crono_tab_parent_class = NULL;
extern cronof_config crono_fconfig;
extern gchar* crono_lcd;
extern cronof_notas crono_ficha[100];
extern sqlite3* crono_db;
extern gint crono_rc;
extern GtkStatusIcon* crono_tray_icon;

GType crono_tab_get_type (void) G_GNUC_CONST;
#define CRONO_TAB_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CRONO_TYPE_TAB, cronotabPrivate))
cronotab* crono_tab_new (gint num);
cronotab* crono_tab_construct (GType object_type,
                               gint num);
void crono_tab_init (cronotab* self,
                     gint num);
GType crono_f_config_get_type (void) G_GNUC_CONST;
cronof_config* crono_f_config_dup (const cronof_config* self);
void crono_f_config_free (cronof_config* self);
void crono_f_config_copy (const cronof_config* self,
                          cronof_config* dest);
void crono_f_config_destroy (cronof_config* self);
static void _gtk_window_close_gtk_widget_destroy (GtkWidget* _sender,
                                           gpointer self);
void crono_tab_click_above (cronotab* self);
static void _crono_tab_click_above_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                    gpointer self);
void crono_tab_diskete (cronotab* self);
static void _crono_tab_diskete_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                gpointer self);
void crono_tab_proteger_nota (cronotab* self);
static void _crono_tab_proteger_nota_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                      gpointer self);
void crono_tab_click_nota_fecha (cronotab* self);
static void _crono_tab_click_nota_fecha_gtk_button_clicked (GtkButton* _sender,
                                                     gpointer self);
gboolean crono_tab_btn_fecha_button_press_event (cronotab* self,
                                                 GdkEventButton* event);
static gboolean _crono_tab_btn_fecha_button_press_event_gtk_widget_button_press_event (GtkWidget* _sender,
                                                                                GdkEventButton* event,
                                                                                gpointer self);
void crono_tab_click_close (cronotab* self);
static void _crono_tab_click_close_gtk_button_clicked (GtkButton* _sender,
                                                gpointer self);
static void __lambda4_ (cronotab* self);
static void ___lambda4__gtk_dialog_close (GtkDialog* _sender,
                                   gpointer self);
void crono_tab_leeFicha (cronotab* self,
                         gint i);
gboolean crono_tab_on_time_1 (cronotab* self);
GType crono_f_notas_get_type (void) G_GNUC_CONST;
cronof_notas* crono_f_notas_dup (const cronof_notas* self);
void crono_f_notas_free (cronof_notas* self);
void crono_f_notas_copy (const cronof_notas* self,
                         cronof_notas* dest);
void crono_f_notas_destroy (cronof_notas* self);
static gboolean _crono_tab_on_time_1_gsource_func (gpointer self);
void crono_guardar (const gchar* nombre,
                    const gchar* nota,
                    const gchar* color,
                    const gchar* id);
void crono_tab_del_ficha (cronotab* self);
static void crono_tab_dialog_response_delete (cronotab* self,
                                       GtkDialog* dialog,
                                       gint response_id);
static void _crono_tab_dialog_response_delete_gtk_dialog_response (GtkDialog* _sender,
                                                            gint response_id,
                                                            gpointer self);
gboolean crono_now_tareas (void);
void crono_tab_proteger (cronotab* self,
                         gint i);
gchar* crono_formatT (gint valor);
gboolean crono_if_tareas_hoy (gint id);
static void crono_tab_finalize (GObject * obj);


cronotab*
crono_tab_construct (GType object_type,
                     gint num)
{
	cronotab * self = NULL;
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self = (cronotab*) g_object_new (object_type, NULL);
#line 34 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_init (self, num);
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return self;
#line 181 "tab.c"
}


cronotab*
crono_tab_new (gint num)
{
#line 33 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return crono_tab_construct (CRONO_TYPE_TAB, num);
#line 190 "tab.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return self ? g_object_ref (self) : NULL;
#line 199 "tab.c"
}


static void
_gtk_window_close_gtk_widget_destroy (GtkWidget* _sender,
                                      gpointer self)
{
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_window_close ((GtkWindow*) self);
#line 209 "tab.c"
}


static void
_crono_tab_click_above_gtk_menu_item_activate (GtkMenuItem* _sender,
                                               gpointer self)
{
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_click_above ((cronotab*) self);
#line 219 "tab.c"
}


static void
_crono_tab_diskete_gtk_menu_item_activate (GtkMenuItem* _sender,
                                           gpointer self)
{
#line 51 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_diskete ((cronotab*) self);
#line 229 "tab.c"
}


static void
_crono_tab_proteger_nota_gtk_menu_item_activate (GtkMenuItem* _sender,
                                                 gpointer self)
{
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_proteger_nota ((cronotab*) self);
#line 239 "tab.c"
}


static void
_crono_tab_click_nota_fecha_gtk_button_clicked (GtkButton* _sender,
                                                gpointer self)
{
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_click_nota_fecha ((cronotab*) self);
#line 249 "tab.c"
}


static gboolean
_crono_tab_btn_fecha_button_press_event_gtk_widget_button_press_event (GtkWidget* _sender,
                                                                       GdkEventButton* event,
                                                                       gpointer self)
{
	gboolean result;
	result = crono_tab_btn_fecha_button_press_event ((cronotab*) self, event);
#line 57 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return result;
#line 262 "tab.c"
}


static void
_crono_tab_click_close_gtk_button_clicked (GtkButton* _sender,
                                           gpointer self)
{
#line 59 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_click_close ((cronotab*) self);
#line 272 "tab.c"
}


static void
__lambda4_ (cronotab* self)
{
	GtkDialog* _tmp0_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->fecha;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_widget_hide (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, gtk_widget_get_type (), GtkWidget));
#line 284 "tab.c"
}


static void
___lambda4__gtk_dialog_close (GtkDialog* _sender,
                              gpointer self)
{
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	__lambda4_ ((cronotab*) self);
#line 294 "tab.c"
}


void
crono_tab_init (cronotab* self,
                gint num)
{
	cronof_config _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GtkImage* _tmp4_;
	cronof_config _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GtkImage* _tmp9_;
	cronof_config _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	GtkImage* _tmp14_;
	cronof_config _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	GtkImage* _tmp19_;
	GDateTime* now = NULL;
	GDateTime* _tmp20_;
	GtkBuilder* _tmp21_;
	GtkBuilder* _tmp22_;
	cronof_config _tmp23_;
	const gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	GtkBuilder* _tmp27_;
	GtkBuilder* _tmp28_;
	GObject* _tmp29_;
	GtkWindow* _tmp30_;
	GtkWindow* _tmp31_;
	GtkWindow* _tmp32_;
	GtkWindow* _tmp33_;
	cronof_config _tmp34_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	GtkBuilder* _tmp38_;
	GObject* _tmp39_;
	GtkCheckMenuItem* _tmp40_;
	GtkCheckMenuItem* _tmp41_;
	GtkBuilder* _tmp42_;
	GObject* _tmp43_;
	GtkMenuItem* _tmp44_;
	GtkMenuItem* _tmp45_;
	GtkBuilder* _tmp46_;
	GObject* _tmp47_;
	GtkMenuItem* _tmp48_;
	GtkMenuItem* _tmp49_;
	GtkBuilder* _tmp50_;
	GObject* _tmp51_;
	GtkButton* _tmp52_;
	GtkButton* _tmp53_;
	GtkBuilder* _tmp54_;
	GObject* _tmp55_;
	GtkButton* _tmp56_;
	GtkButton* _tmp57_;
	GtkBuilder* _tmp58_;
	GObject* _tmp59_;
	GtkButton* _tmp60_;
	GtkButton* _tmp61_;
	GtkBuilder* _tmp62_;
	GObject* _tmp63_;
	GtkTextView* _tmp64_;
	GtkBuilder* _tmp65_;
	GtkBuilder* _tmp66_;
	GObject* _tmp67_;
	GtkDialog* _tmp68_;
	GtkDialog* _tmp69_;
	GtkBuilder* _tmp70_;
	GObject* _tmp71_;
	GtkCalendar* _tmp72_;
	GtkBuilder* _tmp73_;
	GObject* _tmp74_;
	GtkButton* _tmp75_;
	GtkButton* _tmp76_;
	GtkWidget* _tmp77_;
	GtkBuilder* _tmp78_;
	GObject* _tmp79_;
	GtkButton* _tmp80_;
	GtkButton* _tmp81_;
	GtkWidget* _tmp82_;
	GtkCalendar* _tmp83_;
	GDateTime* _tmp84_;
	GtkCalendar* _tmp85_;
	GDateTime* _tmp86_;
	GtkCalendar* _tmp87_;
	GDateTime* _tmp88_;
	GtkWindow* _tmp89_;
	GtkButton* _tmp90_;
	GtkWidget* _tmp91_;
	gint _tmp92_;
	GError * _inner_error_ = NULL;
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = crono_fconfig;
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp1_ = _tmp0_.ruta;
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = g_strconcat (_tmp1_, "minimize.png", NULL);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp3_ = _tmp2_;
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp4_ = (GtkImage*) gtk_image_new_from_file (_tmp3_);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp4_) {
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_object_set_data ((GObject *) _tmp4_, "vala-creation-function", "crono.tab.init");
#line 413 "tab.c"
	}
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_ref_sink (_tmp4_);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->minimize);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->minimize = G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, gtk_widget_get_type (), GtkWidget);
#line 37 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp3_);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp5_ = crono_fconfig;
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp6_ = _tmp5_.ruta;
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp7_ = g_strconcat (_tmp6_, "cerrar.png", NULL);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp8_ = _tmp7_;
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp9_ = (GtkImage*) gtk_image_new_from_file (_tmp8_);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp9_) {
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_object_set_data ((GObject *) _tmp9_, "vala-creation-function", "crono.tab.init");
#line 437 "tab.c"
	}
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_ref_sink (_tmp9_);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->ico_cerrar);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->ico_cerrar = G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, gtk_widget_get_type (), GtkWidget);
#line 38 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp8_);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp10_ = crono_fconfig;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp11_ = _tmp10_.ruta;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp12_ = g_strconcat (_tmp11_, "time.png", NULL);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp13_ = _tmp12_;
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp14_ = (GtkImage*) gtk_image_new_from_file (_tmp13_);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp14_) {
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_object_set_data ((GObject *) _tmp14_, "vala-creation-function", "crono.tab.init");
#line 461 "tab.c"
	}
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_ref_sink (_tmp14_);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->ico_campana);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->ico_campana = G_TYPE_CHECK_INSTANCE_CAST (_tmp14_, gtk_widget_get_type (), GtkWidget);
#line 39 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp13_);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp15_ = crono_fconfig;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp16_ = _tmp15_.ruta;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp17_ = g_strconcat (_tmp16_, "candado.png", NULL);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp18_ = _tmp17_;
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp19_ = (GtkImage*) gtk_image_new_from_file (_tmp18_);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp19_) {
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_object_set_data ((GObject *) _tmp19_, "vala-creation-function", "crono.tab.init");
#line 485 "tab.c"
	}
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_ref_sink (_tmp19_);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->ico_candado);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->ico_candado = G_TYPE_CHECK_INSTANCE_CAST (_tmp19_, gtk_widget_get_type (), GtkWidget);
#line 40 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp18_);
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp20_ = g_date_time_new_now_local ();
#line 41 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	now = _tmp20_;
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp21_ = gtk_builder_new ();
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp21_) {
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_object_set_data ((GObject *) _tmp21_, "vala-creation-function", "crono.tab.init");
#line 505 "tab.c"
	}
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->builder);
#line 42 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->builder = _tmp21_;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp22_ = self->priv->builder;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp23_ = crono_fconfig;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp24_ = _tmp23_.ruta;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp25_ = g_strconcat (_tmp24_, "tab.ui", NULL);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp26_ = _tmp25_;
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_builder_add_from_file (_tmp22_, _tmp26_, &_inner_error_);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp26_);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_date_time_unref0 (now);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_clear_error (&_inner_error_);
#line 43 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		return;
#line 535 "tab.c"
	}
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp27_ = self->priv->builder;
#line 44 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_builder_connect_signals (_tmp27_, NULL);
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp28_ = self->priv->builder;
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp29_ = gtk_builder_get_object (_tmp28_, "tab");
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp30_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp29_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp29_) : NULL);
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->window);
#line 45 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->window = _tmp30_;
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp31_ = self->priv->window;
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp32_ = self->priv->window;
#line 46 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (_tmp31_, gtk_widget_get_type (), GtkWidget), "destroy", (GCallback) _gtk_window_close_gtk_widget_destroy, _tmp32_, 0);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp33_ = self->priv->window;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp34_ = crono_fconfig;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp35_ = _tmp34_.ruta;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp36_ = g_strconcat (_tmp35_, "gnote-panel.png", NULL);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp37_ = _tmp36_;
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_window_set_icon_from_file (_tmp33_, _tmp37_, &_inner_error_);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp37_);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_date_time_unref0 (now);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_clear_error (&_inner_error_);
#line 47 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		return;
#line 581 "tab.c"
	}
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp38_ = self->priv->builder;
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp39_ = gtk_builder_get_object (_tmp38_, "menu_above");
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp40_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp39_, gtk_check_menu_item_get_type ()) ? ((GtkCheckMenuItem*) _tmp39_) : NULL);
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->menu_above);
#line 48 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->menu_above = _tmp40_;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp41_ = self->priv->menu_above;
#line 49 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (_tmp41_, gtk_menu_item_get_type (), GtkMenuItem), "activate", (GCallback) _crono_tab_click_above_gtk_menu_item_activate, self, 0);
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp42_ = self->priv->builder;
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp43_ = gtk_builder_get_object (_tmp42_, "menu_guardar");
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp44_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp43_, gtk_menu_item_get_type ()) ? ((GtkMenuItem*) _tmp43_) : NULL);
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->menu_guardar);
#line 50 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->menu_guardar = _tmp44_;
#line 51 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp45_ = self->priv->menu_guardar;
#line 51 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (_tmp45_, "activate", (GCallback) _crono_tab_diskete_gtk_menu_item_activate, self, 0);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp46_ = self->priv->builder;
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp47_ = gtk_builder_get_object (_tmp46_, "menu_proteger");
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp48_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp47_, gtk_menu_item_get_type ()) ? ((GtkMenuItem*) _tmp47_) : NULL);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->menu_proteger);
#line 52 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->menu_proteger = _tmp48_;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp49_ = self->priv->menu_proteger;
#line 53 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (_tmp49_, "activate", (GCallback) _crono_tab_proteger_nota_gtk_menu_item_activate, self, 0);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp50_ = self->priv->builder;
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp51_ = gtk_builder_get_object (_tmp50_, "nota_fecha");
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp52_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp51_, gtk_button_get_type ()) ? ((GtkButton*) _tmp51_) : NULL);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->nota_fecha);
#line 54 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->nota_fecha = _tmp52_;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp53_ = self->priv->nota_fecha;
#line 55 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (_tmp53_, "clicked", (GCallback) _crono_tab_click_nota_fecha_gtk_button_clicked, self, 0);
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp54_ = self->priv->builder;
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp55_ = gtk_builder_get_object (_tmp54_, "btn_fecha");
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp56_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp55_, gtk_button_get_type ()) ? ((GtkButton*) _tmp55_) : NULL);
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->btn_fecha);
#line 56 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->btn_fecha = _tmp56_;
#line 57 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp57_ = self->priv->btn_fecha;
#line 57 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (_tmp57_, gtk_widget_get_type (), GtkWidget), "button-press-event", (GCallback) _crono_tab_btn_fecha_button_press_event_gtk_widget_button_press_event, self, 0);
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp58_ = self->priv->builder;
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp59_ = gtk_builder_get_object (_tmp58_, "cerrar");
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp60_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp59_, gtk_button_get_type ()) ? ((GtkButton*) _tmp59_) : NULL);
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->cerrar);
#line 58 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->cerrar = _tmp60_;
#line 59 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp61_ = self->priv->cerrar;
#line 59 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (_tmp61_, "clicked", (GCallback) _crono_tab_click_close_gtk_button_clicked, self, 0);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp62_ = self->priv->builder;
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp63_ = gtk_builder_get_object (_tmp62_, "textnota");
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp64_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp63_, gtk_text_view_get_type ()) ? ((GtkTextView*) _tmp63_) : NULL);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->textnota);
#line 60 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->textnota = _tmp64_;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp65_ = self->priv->builder;
#line 61 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_builder_connect_signals (_tmp65_, self);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp66_ = self->priv->builder;
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp67_ = gtk_builder_get_object (_tmp66_, "fecha");
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp68_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp67_, gtk_dialog_get_type ()) ? ((GtkDialog*) _tmp67_) : NULL);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->fecha);
#line 62 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->fecha = _tmp68_;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp69_ = self->priv->fecha;
#line 63 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (_tmp69_, "close", (GCallback) ___lambda4__gtk_dialog_close, self, 0);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp70_ = self->priv->builder;
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp71_ = gtk_builder_get_object (_tmp70_, "calendar");
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp72_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp71_, gtk_calendar_get_type ()) ? ((GtkCalendar*) _tmp71_) : NULL);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->calendar);
#line 64 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->calendar = _tmp72_;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp73_ = self->priv->builder;
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp74_ = gtk_builder_get_object (_tmp73_, "campana");
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp75_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp74_, gtk_button_get_type ()) ? ((GtkButton*) _tmp74_) : NULL);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->campana);
#line 65 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->campana = _tmp75_;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp76_ = self->priv->campana;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp77_ = self->ico_campana;
#line 66 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_button_set_image (_tmp76_, _tmp77_);
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp78_ = self->priv->builder;
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp79_ = gtk_builder_get_object (_tmp78_, "proteger");
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp80_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp79_, gtk_button_get_type ()) ? ((GtkButton*) _tmp79_) : NULL);
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->img_proteger);
#line 67 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->img_proteger = _tmp80_;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp81_ = self->priv->img_proteger;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp82_ = self->ico_candado;
#line 68 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_button_set_image (_tmp81_, _tmp82_);
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp83_ = self->priv->calendar;
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp84_ = now;
#line 69 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_set (_tmp83_, "year", g_date_time_get_year (_tmp84_), NULL);
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp85_ = self->priv->calendar;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp86_ = now;
#line 70 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_set (_tmp85_, "month", g_date_time_get_month (_tmp86_) - 1, NULL);
#line 71 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp87_ = self->priv->calendar;
#line 71 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp88_ = now;
#line 71 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_set (_tmp87_, "day", g_date_time_get_day_of_month (_tmp88_), NULL);
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp89_ = self->priv->window;
#line 72 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_widget_show_all (G_TYPE_CHECK_INSTANCE_CAST (_tmp89_, gtk_widget_get_type (), GtkWidget));
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp90_ = self->priv->cerrar;
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp91_ = self->ico_cerrar;
#line 73 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_button_set_image (_tmp90_, _tmp91_);
#line 74 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv->tmp = num;
#line 75 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp92_ = self->priv->tmp;
#line 75 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_leeFicha (self, _tmp92_);
#line 36 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_date_time_unref0 (now);
#line 773 "tab.c"
}


gboolean
crono_tab_btn_fecha_button_press_event (cronotab* self,
                                        GdkEventButton* event)
{
	gboolean result = FALSE;
	GdkEventType _tmp0_;
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_val_if_fail (CRONO_IS_TAB (self), FALSE);
#line 77 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = event->type;
#line 78 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp0_ == GDK_2BUTTON_PRESS) {
#line 791 "tab.c"
		GtkDialog* _tmp1_;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp1_ = self->priv->fecha;
#line 79 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_show_all (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_widget_get_type (), GtkWidget));
#line 797 "tab.c"
	}
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	result = TRUE;
#line 80 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return result;
#line 803 "tab.c"
}


gboolean
crono_tab_on_time_1 (cronotab* self)
{
	gboolean result = FALSE;
	gboolean _tmp0_;
	gboolean _tmp5_;
#line 82 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_val_if_fail (CRONO_IS_TAB (self), FALSE);
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->state;
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp0_) {
#line 819 "tab.c"
		GtkWindow* _tmp1_;
		const gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp1_ = self->priv->window;
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp2_ = crono_lcd;
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp3_ = g_strconcat ("Nota ", _tmp2_, NULL);
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp4_ = _tmp3_;
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_title (_tmp1_, _tmp4_);
#line 83 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (_tmp4_);
#line 836 "tab.c"
	}
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp5_ = self->priv->state;
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	result = _tmp5_;
#line 84 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return result;
#line 844 "tab.c"
}


static gboolean
_crono_tab_on_time_1_gsource_func (gpointer self)
{
	gboolean result;
	result = crono_tab_on_time_1 ((cronotab*) self);
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	return result;
#line 855 "tab.c"
}


void
crono_tab_click_above (cronotab* self)
{
	GtkCheckMenuItem* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
#line 86 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->menu_above;
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp1_ = gtk_check_menu_item_get_active (_tmp0_);
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = _tmp1_;
#line 87 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp2_) {
#line 875 "tab.c"
		gint _tmp3_;
		cronof_notas _tmp4_;
		gint _tmp5_;
		GtkButton* _tmp7_;
		GtkWidget* _tmp8_;
		GtkWindow* _tmp9_;
		GtkWindow* _tmp10_;
		GtkWindow* _tmp11_;
		GtkWindow* _tmp12_;
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp3_ = self->priv->tmp;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp4_ = crono_ficha[_tmp3_];
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp5_ = _tmp4_.proteger;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		if (_tmp5_ == 1) {
#line 896 "tab.c"
			GtkButton* _tmp6_;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			_tmp6_ = self->priv->cerrar;
#line 88 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 902 "tab.c"
		}
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp7_ = self->priv->cerrar;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp8_ = self->minimize;
#line 89 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_button_set_image (_tmp7_, _tmp8_);
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp9_ = self->priv->window;
#line 90 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_keep_above (_tmp9_, TRUE);
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp10_ = self->priv->window;
#line 91 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_skip_pager_hint (_tmp10_, FALSE);
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp11_ = self->priv->window;
#line 92 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_skip_taskbar_hint (_tmp11_, FALSE);
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp12_ = self->priv->window;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp13_ = crono_lcd;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp14_ = g_strconcat ("Nota ", _tmp13_, NULL);
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp15_ = _tmp14_;
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_title (_tmp12_, _tmp15_);
#line 93 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (_tmp15_);
#line 94 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		self->priv->state = TRUE;
#line 95 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		self->priv->time_bar = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _crono_tab_on_time_1_gsource_func, g_object_ref (self), g_object_unref);
#line 938 "tab.c"
	} else {
		gint _tmp16_;
		cronof_notas _tmp17_;
		gint _tmp18_;
		GtkButton* _tmp20_;
		GtkWidget* _tmp21_;
		GtkWindow* _tmp22_;
		GtkWindow* _tmp23_;
		GtkWindow* _tmp24_;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp16_ = self->priv->tmp;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp17_ = crono_ficha[_tmp16_];
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp18_ = _tmp17_.proteger;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		if (_tmp18_ == 1) {
#line 956 "tab.c"
			GtkButton* _tmp19_;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			_tmp19_ = self->priv->cerrar;
#line 98 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp19_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 962 "tab.c"
		}
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp20_ = self->priv->cerrar;
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp21_ = self->ico_cerrar;
#line 99 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_button_set_image (_tmp20_, _tmp21_);
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp22_ = self->priv->window;
#line 100 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_keep_above (_tmp22_, FALSE);
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp23_ = self->priv->window;
#line 101 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_skip_pager_hint (_tmp23_, TRUE);
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp24_ = self->priv->window;
#line 102 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_set_skip_taskbar_hint (_tmp24_, TRUE);
#line 103 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		self->priv->state = FALSE;
#line 984 "tab.c"
	}
}


void
crono_tab_diskete (cronotab* self)
{
	gint _tmp0_;
	gint _tmp1_;
	GtkTextView* _tmp2_;
	GtkTextBuffer* _tmp3_;
	GtkTextBuffer* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gint _tmp7_;
	cronof_notas _tmp8_;
	const gchar* _tmp9_;
	GtkTextView* _tmp10_;
	GtkTextBuffer* _tmp11_;
	GtkTextBuffer* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gint _tmp16_;
	cronof_notas _tmp17_;
	const gchar* _tmp18_;
	gint _tmp19_;
	cronof_notas _tmp20_;
	const gchar* _tmp21_;
#line 106 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->tmp;
#line 107 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_ficha[_tmp0_].visible = TRUE;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp1_ = self->priv->tmp;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = self->priv->textnota;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp3_ = gtk_text_view_get_buffer (_tmp2_);
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp4_ = _tmp3_;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp4_, "text", &_tmp5_, NULL);
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp6_ = _tmp5_;
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (crono_ficha[_tmp1_].nota);
#line 108 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_ficha[_tmp1_].nota = _tmp6_;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp7_ = self->priv->tmp;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp8_ = crono_ficha[_tmp7_];
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp9_ = _tmp8_.nombre;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp10_ = self->priv->textnota;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp11_ = gtk_text_view_get_buffer (_tmp10_);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp12_ = _tmp11_;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp12_, "text", &_tmp13_, NULL);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp14_ = _tmp13_;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp15_ = _tmp14_;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp16_ = self->priv->tmp;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp17_ = crono_ficha[_tmp16_];
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp18_ = _tmp17_.color;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp19_ = self->priv->tmp;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp20_ = crono_ficha[_tmp19_];
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp21_ = _tmp20_.id;
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_guardar (_tmp9_, _tmp15_, _tmp18_, _tmp21_);
#line 109 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp15_);
#line 1070 "tab.c"
}


static void
_crono_tab_dialog_response_delete_gtk_dialog_response (GtkDialog* _sender,
                                                       gint response_id,
                                                       gpointer self)
{
#line 114 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_dialog_response_delete ((cronotab*) self, _sender, response_id);
#line 1081 "tab.c"
}


void
crono_tab_del_ficha (cronotab* self)
{
	GtkMessageDialog* messagedialog = NULL;
	GtkMessageDialog* _tmp0_;
#line 111 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = (GtkMessageDialog*) gtk_message_dialog_new (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_window_get_type (), GtkWindow), GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK_CANCEL, "Esta Seguro que desea Borrar la Nota.. ?");
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp0_) {
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_object_set_data ((GObject *) _tmp0_, "vala-creation-function", "crono.tab.del_ficha");
#line 1098 "tab.c"
	}
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_ref_sink (_tmp0_);
#line 112 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	messagedialog = _tmp0_;
#line 114 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (messagedialog, gtk_dialog_get_type (), GtkDialog), "response", (GCallback) _crono_tab_dialog_response_delete_gtk_dialog_response, self, 0);
#line 115 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_widget_show (G_TYPE_CHECK_INSTANCE_CAST (messagedialog, gtk_widget_get_type (), GtkWidget));
#line 111 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (messagedialog);
#line 1110 "tab.c"
}


static gint
_sqlite3_exec (sqlite3* self,
               const gchar* sql,
               sqlite3_callback callback,
               gpointer callback_target,
               gchar* * errmsg)
{
	gchar* _vala_errmsg = NULL;
	gint result = 0;
	const gchar* sqlite_errmsg = NULL;
	gint ec = 0;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_;
	const gchar* _tmp4_;
#line 34 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 34 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	g_return_val_if_fail (sql != NULL, 0);
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	_tmp1_ = sqlite3_exec (self, sql, callback, callback_target, (char**) (&_tmp0_));
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	sqlite_errmsg = _tmp0_;
#line 36 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	ec = _tmp1_;
#line 37 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	if ((&_vala_errmsg) != NULL) {
#line 1140 "tab.c"
		const gchar* _tmp2_;
		gchar* _tmp3_;
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_tmp2_ = sqlite_errmsg;
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_tmp3_ = g_strdup (_tmp2_);
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_g_free0 (_vala_errmsg);
#line 38 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_vala_errmsg = _tmp3_;
#line 1151 "tab.c"
	}
#line 40 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	_tmp4_ = sqlite_errmsg;
#line 40 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	sqlite3_free ((void*) _tmp4_);
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	result = ec;
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	if (errmsg) {
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		*errmsg = _vala_errmsg;
#line 1163 "tab.c"
	} else {
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
		_g_free0 (_vala_errmsg);
#line 1167 "tab.c"
	}
#line 41 "/usr/share/vala-0.40/vapi/sqlite3.vapi"
	return result;
#line 1171 "tab.c"
}


static void
crono_tab_dialog_response_delete (cronotab* self,
                                  GtkDialog* dialog,
                                  gint response_id)
{
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 117 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (GTK_IS_DIALOG (dialog));
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	switch (response_id) {
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		case GTK_RESPONSE_OK:
#line 1188 "tab.c"
		{
			{
				gchar* errmsg = NULL;
				gchar* query = NULL;
				gint _tmp0_;
				cronof_notas _tmp1_;
				const gchar* _tmp2_;
				gchar* _tmp3_;
				gchar* _tmp4_;
				gchar* _tmp5_;
				gchar* _tmp6_;
				sqlite3* _tmp7_;
				const gchar* _tmp8_;
				gchar* _tmp9_ = NULL;
				gint _tmp10_;
				gint _tmp11_;
				GtkWindow* _tmp13_;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp0_ = self->priv->tmp;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp1_ = crono_ficha[_tmp0_];
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp2_ = _tmp1_.id;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp3_ = g_strconcat ("DELETE FROM nota WHERE id=", _tmp2_, NULL);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp4_ = _tmp3_;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp5_ = g_strconcat (_tmp4_, ";", NULL);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp6_ = _tmp5_;
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_g_free0 (_tmp4_);
#line 121 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				query = _tmp6_;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp7_ = crono_db;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp8_ = query;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp10_ = _sqlite3_exec (_tmp7_, _tmp8_, NULL, NULL, &_tmp9_);
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_g_free0 (errmsg);
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				errmsg = _tmp9_;
#line 122 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				crono_rc = _tmp10_;
#line 123 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp11_ = crono_rc;
#line 123 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				if (_tmp11_ != SQLITE_OK) {
#line 1240 "tab.c"
					const gchar* _tmp12_;
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp12_ = errmsg;
#line 124 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					g_print ("Error: %s\n", _tmp12_);
#line 1246 "tab.c"
				}
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_tmp13_ = self->priv->window;
#line 125 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				gtk_widget_destroy (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, gtk_widget_get_type (), GtkWidget));
#line 126 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				if (crono_now_tareas ()) {
#line 1254 "tab.c"
					GtkStatusIcon* _tmp14_;
					cronof_config _tmp15_;
					const gchar* _tmp16_;
					gchar* _tmp17_;
					gchar* _tmp18_;
					GtkStatusIcon* _tmp19_;
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp14_ = crono_tray_icon;
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp15_ = crono_fconfig;
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp16_ = _tmp15_.ruta;
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp17_ = g_strconcat (_tmp16_, "gnote-panel-1.png", NULL);
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp18_ = _tmp17_;
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					gtk_status_icon_set_from_file (_tmp14_, _tmp18_);
#line 127 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_g_free0 (_tmp18_);
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp19_ = crono_tray_icon;
#line 128 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					gtk_status_icon_set_tooltip_text (_tmp19_, "Tiene Notas Para Hoy...");
#line 1279 "tab.c"
				} else {
					GtkStatusIcon* _tmp20_;
					cronof_config _tmp21_;
					const gchar* _tmp22_;
					gchar* _tmp23_;
					gchar* _tmp24_;
					GtkStatusIcon* _tmp25_;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp20_ = crono_tray_icon;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp21_ = crono_fconfig;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp22_ = _tmp21_.ruta;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp23_ = g_strconcat (_tmp22_, "gnote-panel.png", NULL);
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp24_ = _tmp23_;
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					gtk_status_icon_set_from_file (_tmp20_, _tmp24_);
#line 131 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_g_free0 (_tmp24_);
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					_tmp25_ = crono_tray_icon;
#line 132 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
					gtk_status_icon_set_tooltip_text (_tmp25_, "Cronotas 0.2 - Sin Notas Pendientes");
#line 1305 "tab.c"
				}
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_g_free0 (query);
#line 119 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
				_g_free0 (errmsg);
#line 1311 "tab.c"
			}
#line 135 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			break;
#line 1315 "tab.c"
		}
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		case GTK_RESPONSE_CANCEL:
#line 1319 "tab.c"
		{
#line 137 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			g_print ("good choice\n");
#line 138 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			break;
#line 1325 "tab.c"
		}
		default:
#line 118 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		break;
#line 1330 "tab.c"
	}
#line 140 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_widget_destroy (G_TYPE_CHECK_INSTANCE_CAST (dialog, gtk_widget_get_type (), GtkWidget));
#line 1334 "tab.c"
}


void
crono_tab_proteger_nota (cronotab* self)
{
	gchar* errmsg = NULL;
	gchar* query = NULL;
	gint _tmp0_;
	cronof_notas _tmp1_;
	gint _tmp2_;
	gint _tmp29_;
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 145 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->tmp;
#line 145 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp1_ = crono_ficha[_tmp0_];
#line 145 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = _tmp1_.proteger;
#line 145 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp2_ == 0) {
#line 1357 "tab.c"
		gint _tmp3_;
		gint _tmp4_;
		cronof_notas _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		sqlite3* _tmp10_;
		const gchar* _tmp11_;
		gchar* _tmp12_ = NULL;
		gint _tmp13_;
		gint _tmp14_;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp3_ = self->priv->tmp;
#line 146 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		crono_ficha[_tmp3_].proteger = 1;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp4_ = self->priv->tmp;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp5_ = crono_ficha[_tmp4_];
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp6_ = _tmp5_.id;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp7_ = g_strconcat ("UPDATE nota SET proteger=1 WHERE id=", _tmp6_, NULL);
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp8_ = _tmp7_;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp9_ = g_strconcat (_tmp8_, ";", NULL);
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (query);
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		query = _tmp9_;
#line 147 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (_tmp8_);
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp10_ = crono_db;
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp11_ = query;
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp13_ = _sqlite3_exec (_tmp10_, _tmp11_, NULL, NULL, &_tmp12_);
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (errmsg);
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		errmsg = _tmp12_;
#line 148 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		crono_rc = _tmp13_;
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp14_ = crono_rc;
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		if (_tmp14_ != SQLITE_OK) {
#line 1408 "tab.c"
			const gchar* _tmp15_;
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			_tmp15_ = errmsg;
#line 149 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			g_print ("Error: %s\n", _tmp15_);
#line 1414 "tab.c"
		}
	} else {
		gint _tmp16_;
		gint _tmp17_;
		cronof_notas _tmp18_;
		const gchar* _tmp19_;
		gchar* _tmp20_;
		gchar* _tmp21_;
		gchar* _tmp22_;
		sqlite3* _tmp23_;
		const gchar* _tmp24_;
		gchar* _tmp25_ = NULL;
		gint _tmp26_;
		gint _tmp27_;
#line 153 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp16_ = self->priv->tmp;
#line 153 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		crono_ficha[_tmp16_].proteger = 0;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp17_ = self->priv->tmp;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp18_ = crono_ficha[_tmp17_];
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp19_ = _tmp18_.id;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp20_ = g_strconcat ("UPDATE nota SET proteger=0 WHERE id=", _tmp19_, NULL);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp21_ = _tmp20_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp22_ = g_strconcat (_tmp21_, ";", NULL);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (query);
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		query = _tmp22_;
#line 154 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (_tmp21_);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp23_ = crono_db;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp24_ = query;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp26_ = _sqlite3_exec (_tmp23_, _tmp24_, NULL, NULL, &_tmp25_);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (errmsg);
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		errmsg = _tmp25_;
#line 155 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		crono_rc = _tmp26_;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp27_ = crono_rc;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		if (_tmp27_ != SQLITE_OK) {
#line 1467 "tab.c"
			const gchar* _tmp28_;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			_tmp28_ = errmsg;
#line 156 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
			g_print ("Error: %s\n", _tmp28_);
#line 1473 "tab.c"
		}
	}
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp29_ = self->priv->tmp;
#line 158 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_leeFicha (self, _tmp29_);
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (query);
#line 142 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (errmsg);
#line 1484 "tab.c"
}


void
crono_tab_proteger (cronotab* self,
                    gint i)
{
#line 160 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 161 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (i == 0) {
#line 1496 "tab.c"
		GtkMenuItem* _tmp0_;
		GtkButton* _tmp1_;
		GtkButton* _tmp2_;
		GtkMenuItem* _tmp3_;
		GtkButton* _tmp4_;
		GtkTextView* _tmp5_;
		GtkButton* _tmp6_;
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp0_ = self->priv->menu_proteger;
#line 162 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_menu_item_set_label (_tmp0_, "Proteger Nota");
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp1_ = self->priv->cerrar;
#line 163 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp2_ = self->priv->cerrar;
#line 164 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp3_ = self->priv->menu_guardar;
#line 165 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp4_ = self->priv->btn_fecha;
#line 166 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp5_ = self->priv->textnota;
#line 167 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_text_view_set_editable (_tmp5_, TRUE);
#line 168 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp6_ = self->priv->img_proteger;
#line 168 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 1532 "tab.c"
	} else {
		GtkMenuItem* _tmp7_;
		GtkButton* _tmp8_;
		GtkButton* _tmp9_;
		GtkMenuItem* _tmp10_;
		GtkButton* _tmp11_;
		GtkTextView* _tmp12_;
		GtkButton* _tmp13_;
#line 172 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp7_ = self->priv->menu_proteger;
#line 172 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_menu_item_set_label (_tmp7_, "Desproteger Nota");
#line 173 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp8_ = self->priv->cerrar;
#line 173 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 174 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp9_ = self->priv->cerrar;
#line 174 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 175 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp10_ = self->priv->menu_guardar;
#line 175 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp10_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 176 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp11_ = self->priv->btn_fecha;
#line 176 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_sensitive (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 177 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp12_ = self->priv->textnota;
#line 177 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_text_view_set_editable (_tmp12_, FALSE);
#line 178 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp13_ = self->priv->img_proteger;
#line 178 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 1569 "tab.c"
	}
}


void
crono_tab_click_nota_fecha (cronotab* self)
{
	gchar* mi_fecha = NULL;
	GtkCalendar* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GtkCalendar* _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	GtkCalendar* _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* errmsg = NULL;
	gchar* query = NULL;
	const gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	GtkTextView* _tmp28_;
	GtkTextBuffer* _tmp29_;
	GtkTextBuffer* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	gint _tmp38_;
	cronof_notas _tmp39_;
	const gchar* _tmp40_;
	gchar* _tmp41_;
	gchar* _tmp42_;
	gchar* _tmp43_;
	gchar* _tmp44_;
	sqlite3* _tmp45_;
	const gchar* _tmp46_;
	gchar* _tmp47_ = NULL;
	gint _tmp48_;
	gint _tmp49_;
	const gchar* _tmp50_;
	gchar* _tmp51_;
	gint _tmp52_;
	GtkTextView* _tmp53_;
	GtkTextBuffer* _tmp54_;
	GtkTextBuffer* _tmp55_;
	gchar* _tmp56_;
	gchar* _tmp57_;
	gint _tmp58_;
	gint _tmp59_;
	GtkDialog* _tmp61_;
#line 181 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->calendar;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp0_, "day", &_tmp1_, NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = _tmp1_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp3_ = crono_formatT (_tmp2_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp4_ = _tmp3_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp5_ = g_strconcat (_tmp4_, "/", NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp6_ = _tmp5_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp7_ = self->priv->calendar;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp7_, "month", &_tmp8_, NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp9_ = _tmp8_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp10_ = crono_formatT (_tmp9_ + 1);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp11_ = _tmp10_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp12_ = g_strconcat (_tmp6_, _tmp11_, NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp13_ = _tmp12_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp14_ = g_strconcat (_tmp13_, "/", NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp15_ = _tmp14_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp16_ = self->priv->calendar;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp16_, "year", &_tmp17_, NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp18_ = _tmp17_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp19_ = g_strdup_printf ("%i", _tmp18_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp20_ = _tmp19_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp21_ = g_strconcat (_tmp15_, _tmp20_, NULL);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp22_ = _tmp21_;
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp20_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp15_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp13_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp11_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp6_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp4_);
#line 182 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	mi_fecha = _tmp22_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp23_ = mi_fecha;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp24_ = g_strconcat ("UPDATE nota SET fecha='", _tmp23_, NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp25_ = _tmp24_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp26_ = g_strconcat (_tmp25_, "', nota='", NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp27_ = _tmp26_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp28_ = self->priv->textnota;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp29_ = gtk_text_view_get_buffer (_tmp28_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp30_ = _tmp29_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp30_, "text", &_tmp31_, NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp32_ = _tmp31_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp33_ = _tmp32_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp34_ = g_strconcat (_tmp27_, _tmp33_, NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp35_ = _tmp34_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp36_ = g_strconcat (_tmp35_, "' WHERE id=", NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp37_ = _tmp36_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp38_ = self->priv->tmp;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp39_ = crono_ficha[_tmp38_];
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp40_ = _tmp39_.id;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp41_ = g_strconcat (_tmp37_, _tmp40_, NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp42_ = _tmp41_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp43_ = g_strconcat (_tmp42_, ";", NULL);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp44_ = _tmp43_;
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp42_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp37_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp35_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp33_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp27_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (_tmp25_);
#line 184 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	query = _tmp44_;
#line 185 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp45_ = crono_db;
#line 185 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp46_ = query;
#line 185 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp48_ = _sqlite3_exec (_tmp45_, _tmp46_, NULL, NULL, &_tmp47_);
#line 185 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (errmsg);
#line 185 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	errmsg = _tmp47_;
#line 185 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_rc = _tmp48_;
#line 186 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp49_ = self->priv->tmp;
#line 186 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp50_ = mi_fecha;
#line 186 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp51_ = g_strdup (_tmp50_);
#line 186 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (crono_ficha[_tmp49_].fecha);
#line 186 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_ficha[_tmp49_].fecha = _tmp51_;
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp52_ = self->priv->tmp;
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp53_ = self->priv->textnota;
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp54_ = gtk_text_view_get_buffer (_tmp53_);
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp55_ = _tmp54_;
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_get (_tmp55_, "text", &_tmp56_, NULL);
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp57_ = _tmp56_;
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (crono_ficha[_tmp52_].nota);
#line 187 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_ficha[_tmp52_].nota = _tmp57_;
#line 188 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp58_ = self->priv->tmp;
#line 188 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_leeFicha (self, _tmp58_);
#line 189 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp59_ = crono_rc;
#line 189 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp59_ != SQLITE_OK) {
#line 1807 "tab.c"
		const gchar* _tmp60_;
#line 189 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp60_ = errmsg;
#line 189 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		g_print ("Error: %s\n", _tmp60_);
#line 1813 "tab.c"
	}
#line 190 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp61_ = self->priv->fecha;
#line 190 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_widget_hide (G_TYPE_CHECK_INSTANCE_CAST (_tmp61_, gtk_widget_get_type (), GtkWidget));
#line 181 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (query);
#line 181 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (errmsg);
#line 181 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_free0 (mi_fecha);
#line 1825 "tab.c"
}


void
crono_tab_click_close (cronotab* self)
{
	GtkCheckMenuItem* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
#line 192 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 193 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->menu_above;
#line 193 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp1_ = gtk_check_menu_item_get_active (_tmp0_);
#line 193 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = _tmp1_;
#line 193 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (_tmp2_) {
#line 1845 "tab.c"
		GtkWindow* _tmp3_;
#line 194 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp3_ = self->priv->window;
#line 194 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_window_iconify (_tmp3_);
#line 1851 "tab.c"
	} else {
#line 196 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		crono_tab_del_ficha (self);
#line 1855 "tab.c"
	}
}


void
crono_tab_leeFicha (cronotab* self,
                    gint i)
{
	GtkTextView* _tmp0_;
	GtkTextBuffer* _tmp1_;
	GtkTextBuffer* _tmp2_;
	GtkTextView* _tmp3_;
	GtkTextBuffer* _tmp4_;
	GtkTextBuffer* _tmp5_;
	cronof_notas _tmp6_;
	const gchar* _tmp7_;
	GtkButton* _tmp8_;
	cronof_notas _tmp9_;
	const gchar* _tmp10_;
	cronof_notas _tmp11_;
	gint _tmp12_;
	cronof_notas _tmp13_;
	const gchar* _tmp14_;
#line 198 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_return_if_fail (CRONO_IS_TAB (self));
#line 199 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp0_ = self->priv->textnota;
#line 199 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp1_ = gtk_text_view_get_buffer (_tmp0_);
#line 199 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp2_ = _tmp1_;
#line 199 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_set (_tmp2_, "text", "", NULL);
#line 200 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp3_ = self->priv->textnota;
#line 200 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp4_ = gtk_text_view_get_buffer (_tmp3_);
#line 200 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp5_ = _tmp4_;
#line 200 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp6_ = crono_ficha[i];
#line 200 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp7_ = _tmp6_.nota;
#line 200 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_object_set (_tmp5_, "text", _tmp7_, NULL);
#line 201 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp8_ = self->priv->btn_fecha;
#line 201 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp9_ = crono_ficha[i];
#line 201 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp10_ = _tmp9_.fecha;
#line 201 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	gtk_button_set_label (_tmp8_, _tmp10_);
#line 202 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp11_ = crono_ficha[i];
#line 202 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp12_ = _tmp11_.proteger;
#line 202 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_proteger (self, _tmp12_);
#line 203 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp13_ = crono_ficha[i];
#line 203 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_tmp14_ = _tmp13_.id;
#line 203 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	if (crono_if_tareas_hoy (atoi (_tmp14_))) {
#line 1921 "tab.c"
		GtkButton* _tmp15_;
		GtkStatusIcon* _tmp16_;
		cronof_config _tmp17_;
		const gchar* _tmp18_;
		gchar* _tmp19_;
		gchar* _tmp20_;
		GtkStatusIcon* _tmp21_;
#line 204 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp15_ = self->priv->campana;
#line 204 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp15_, gtk_widget_get_type (), GtkWidget), TRUE);
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp16_ = crono_tray_icon;
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp17_ = crono_fconfig;
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp18_ = _tmp17_.ruta;
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp19_ = g_strconcat (_tmp18_, "gnote-panel-1.png", NULL);
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp20_ = _tmp19_;
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_status_icon_set_from_file (_tmp16_, _tmp20_);
#line 205 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (_tmp20_);
#line 206 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp21_ = crono_tray_icon;
#line 206 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_status_icon_set_tooltip_text (_tmp21_, "Tiene Notas Para Hoy...");
#line 1951 "tab.c"
	} else {
		GtkButton* _tmp22_;
		GtkStatusIcon* _tmp23_;
		cronof_config _tmp24_;
		const gchar* _tmp25_;
		gchar* _tmp26_;
		gchar* _tmp27_;
		GtkStatusIcon* _tmp28_;
#line 209 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp22_ = self->priv->campana;
#line 209 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_widget_set_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp22_, gtk_widget_get_type (), GtkWidget), FALSE);
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp23_ = crono_tray_icon;
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp24_ = crono_fconfig;
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp25_ = _tmp24_.ruta;
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp26_ = g_strconcat (_tmp25_, "gnote-panel.png", NULL);
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp27_ = _tmp26_;
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_status_icon_set_from_file (_tmp23_, _tmp27_);
#line 210 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_g_free0 (_tmp27_);
#line 211 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		_tmp28_ = crono_tray_icon;
#line 211 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
		gtk_status_icon_set_tooltip_text (_tmp28_, "Cronotas 0.2 - Sin Notas Pendientes");
#line 1982 "tab.c"
	}
}


static void
crono_tab_class_init (cronotabClass * klass)
{
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	crono_tab_parent_class = g_type_class_peek_parent (klass);
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	g_type_class_add_private (klass, sizeof (cronotabPrivate));
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	G_OBJECT_CLASS (klass)->finalize = crono_tab_finalize;
#line 1996 "tab.c"
}


static void
crono_tab_instance_init (cronotab * self)
{
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self->priv = CRONO_TAB_GET_PRIVATE (self);
#line 2005 "tab.c"
}


static void
crono_tab_finalize (GObject * obj)
{
	cronotab * self;
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CRONO_TYPE_TAB, cronotab);
#line 13 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->builder);
#line 14 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->window);
#line 15 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->btn_fecha);
#line 16 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->cerrar);
#line 17 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->nota_fecha);
#line 18 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->textnota);
#line 19 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->calendar);
#line 20 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->fecha);
#line 21 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->menu_proteger);
#line 22 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->menu_above);
#line 23 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->menu_guardar);
#line 24 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->campana);
#line 25 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->priv->img_proteger);
#line 26 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->minimize);
#line 27 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->ico_cerrar);
#line 28 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->ico_campana);
#line 29 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	_g_object_unref0 (self->ico_candado);
#line 12 "/home/didapax/Yandex.Disk/proyectos/vala/cronotas.0.2.1/tab.vala"
	G_OBJECT_CLASS (crono_tab_parent_class)->finalize (obj);
#line 2051 "tab.c"
}


GType
crono_tab_get_type (void)
{
	static volatile gsize crono_tab_type_id__volatile = 0;
	if (g_once_init_enter (&crono_tab_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (cronotabClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) crono_tab_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (cronotab), 0, (GInstanceInitFunc) crono_tab_instance_init, NULL };
		GType crono_tab_type_id;
		crono_tab_type_id = g_type_register_static (gtk_window_get_type (), "cronotab", &g_define_type_info, 0);
		g_once_init_leave (&crono_tab_type_id__volatile, crono_tab_type_id);
	}
	return crono_tab_type_id__volatile;
}



